var eg_full = {
  "Sune": ["(U') F' L U2 F2 R U' x'", "R U R' F2 U F R U R' ", "(U') R' F R U2 R U' R2 F2 R F'","F' U R U' R' U F R U R'", "(U) R U' R' U R U' R' U F R U' R'", "R' F R2 U' R' U L F' L' F"],
  "AntiSune": ["(U') B U' R2 F2 U' F" , "(U) R U' R' F' U' F2 R U' R'","F' R U R' U' R U R2' F' R","R U' R' F' U' R U R' U' F", " (U') R U R' F' U' R U R' U' R U R'", "(U2) R U' R2 F R U' R' F R F'"],
  "Pi": ["(U2) R2 B2 R' U R' U' R U2 R U' R2", "(U') R' F R2 U' R2 F R", "(U') F R' F U' F2 R U R"," (U') R U' R' U R U' R' F R U' R'", "(U) F U' R U2 R' F' R U R' F'", "F R U' R' F R U2 R' U F'"],
  "U" : ["R U' R2' F R2 U R' U' R U' R'", "(U2) x U' R' U R U' F R U R U'", "(U) F' U2 R U2 R' U2 F","(U2) R' F R F' R' F R2 U' R'", "(U2) R' F R F' U R U' R' F R U' R'", "(U') R' F R2 U' R' U y' R U R'"],
  "L" : ["R U' R' U R U' R2 F' R F", "(U2) (F R' F' R) U2 R U' R2 F' R2 U R'", "R' U R2 U' R2 U' F R2 U' R'","R' F R2 U R' F' R U2 R'", "(U) L' U L y' R U2 R U' R2", "(U) R' U2' F R U2 R U' R2 F"],
  "T" : ["(U2) R2 U R U' R2 F R U2 R' F", "(U2) R2 U R U' R2 F R U2 R' F", "(U2) R U' R2 F R U R U2 R'","R2 B2 U' R' U' R U' R' U R'", "(U2) R U R2 x U' R U R' U' R", "(U') R U' R' U2 F R U2 R' F"],
  "H" : ["R' F R2 U' R2 U' F U R", "F' U R U' R2 F2 R U' F", " R' U' R' F2 U F' R F'", "R U R' F' R U R' U' R U R' U'"]
}

var zbll_full = {
    
    "T1": ["(U') R U R' U R U2 R' U2 R' U' R U' R' U2 R", "R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'", "(U2) R' U2 R U R' U R2 U2 R' U' R U' R'", "R U2 R' U' R U' R2 U2 R U R' U R", "R' U R U2 R' U' R U2 R' U' R U' R' U R", "(U2) R U' R' U2 R U R' U2 R U R' U R U' R'", "R' U R2 U R' U R' U' R U' R' U' R U R U' R'", "(U') R U R' U R U' R' U R' U' R2 U' R2 U2 R", "(U2) R' U2 R U R' U R U' R' U' R U' R' U2 R", "R U2 R' U' R U' R' U R U R'U R U2 R'", "(U') R' U' R2 U R2 U R2 U2 R' U R' U R ", "(U') R U R2 U' R2 U' R2 U2 R U' R U' R'"],
    "T2": ["(U) R U R' U R U R2 D' r U2 r' D R2 U R'", "(U) R' U' R U' R' U' R2 D r' U2 r D' R2 U' R", "(U2) R U' R2 D' r U2 r' D R2 U R'", "R' U R2 D r' U2 r D' R2 U' R", "R' U' R U2 R D R' U' R D' R2 U R U' R' U R", "(U') R U2 R' U' R U r' F r U2 R' r' F r", "R' U' R U R2 D' R U2 R' D R2 U2 R' U2 R", "(U) R U R' U' R U R2 D' R U' R' D R U2 R U' R'", "(U) R' D' R U' R' D R U' R U' R' U R U' R' U' R U R'", "R U' R' U R U R' U' R U R' U R' D' R U R' D R", "(U) R U R D R' U R D' R' U L' U R' U' L ", "(U2) R2 F R U R' U' R' F' R' U' R2 U2 R U2 R"],
    "T3": ["R' U R U2 L' R' U R U' L ", "R' U2 R U R2 F R U R U' R' F' R", "(U2) R' U' R2 U R' F' R U R' U' R' F R2 U' R' U' R' U R", "(U2) r U' r U2 R' F R U2 r2 F", "(U') R' U' R' D' R U R' D R U2 R U R' U R", "R' U' R y R U R' U' R l U' R' U l'", "(U) L' U2 R U2 R' U2 L U R U R' U' R U' R'", "F U' R' U2 R U F' R' U' R U R' U R", "(U2) R' U' R U' R' U R F U' R' U2 R U F'", "R U R' U R U' R' U' L' U2 R U2 R' U2 L", "R' U2 R U R' U R F U R U2 R' U R U R' F'", "r' U' l' U2 R U' R' U2 l R U' R' U2 r"],
    "T4": ["(U') l' U2 R' D2 R U2 R' D2 R2 x'", "R' U2 R U' R' F R U R' U' R' F' R U' R", "R' U2 R' D' R U2 R' D R' U R' U R U2 R'", "(U2) R U2 R D R' U2 R D' R U' R U' R' U2 R", "R' D' R U R' D R U2 R U2 R' U R U R'", "(U) R' U' R' D' R U R' D R U' R U' R' U2 R", "R' U R2 D R' U R D' R' U R' U' R U' R' U' R ", "(U2) R U' R2 D' R U' R' D R U' R U R' U R U R'", "(U) R' U' R U' F U' R' U R U F' R' U R", "R' D' R U R' D R2 U R' U2 R U' R' U' R U' R'", "(U2) F R U R' U' R U' R' U' R U R' F'", "(U') R U R' U2 R U' R' U2 R U' R2 F' R U R U' R' F"],
    "T5": ["R U R D R' U' R D' R2", "(U') R U2 R' U2 R' F R U R U' R' F'", "(U2) R2 B2 R' U2 R' U2 R B2 R' U R U' R'", "(U') R' D' R U R' D R2 U' R' U R U R' U' R U R'", "(U') F' U' r' F2 r U' r' F' r F ", "(U') R U R' U' R U' R' L U' R U R' L'", "(U) R U R' U R U R' U2 L R U' R' U L'", "R' U' R U' R2' F' R U R U' R' F U R U' R' U2 R", "(U) R' U' R U R' U' R2 D R' U2 R D' R' U R' U R", "(U2) R U R D R' U2 R D' R' U' R' U R U' R' U' R U' R'", "(U2) F R U R' U' R' F' U2 R U R U' R2 U2 R", "(U') R U' R' U' R U R D R' U2 R D' R' U' R'"],
    "T6": ["x' U' R' D R U R' D' R x", "(U) R U R' U' R' F' R U2 R U2 R' F", "R2 F2 R U2 R U2 R' F2 R U' R' U R", "(U') R D R' U' R D' R2 U R U' R' U' R U R' U' R", "(U) F U R U2 R' U R U R' F'", "R U R' U' R U' R'  U' F R U R' U' R' F' R", "(U) R' U' R U' R' U' R U2 L' R' U R U' L", "(U) F R U R' U' R U R' U' F' R U R' U' R' F R F'", "(U) R U R' U' R U R2 D' R U2 R' D R U' R U' R'", "R' U2 R F U' R' U R U F' R' U R", "(U) R' U2 R2 U R' U' R' U2 F' R U2 R U2 R' F", "(U') R' U R U R' U' R' D' R U2 R' D R U R"],

    "U1": ["(U) R U2 R' U' R U' R' U2 R' U2 R U R' U R", "R U R' U' R U' R U2 R2 U' R U R' U' R2 U' R2", "R' U' R U' R' U2 R2 U R' U R U2 R'", "(U2) R U R' U R U2 R2 U' R U' R' U2 R", "(U') R U R' U' R U' R' U2 R U' R' U2 R U R'", "(U') R' U' R U R' U R U2 R' U R U2 R' U' R", "(U) R U2 R2 U' R2 U' R' U R' U' R U R' U R", "(U) R' U2 R2 U R2 U R U' R U R' U' R U' R'", "(U) R' U2 R U R' U R U R' U' R U' R' U2 R", "(U) R U2 R' U' R U' R' U' R U R' U R U2 R'", "R' U' R U' R U2 R2 U' R2 U' R2 U R", "(U2) R U R' U R' U2 R2 U R2 U R2 U' R'"],
    "U2": ["(U2) R' U' R U' F U' R' U R U R' U R U' F'", "R U R' U L' U R U' M' x' U' R U' R'", "(U') R U2 R2 F R F' M' U' R U' R' U M", "(U') R' U2 R F U' R' U R U R' U R U' F'", "(U2)  R2 D R' U' R D' R' U' R' U R U R'", "R2 D' R U R' D R U R U' R' U' R", "R U' R' U' R U R D R' U R D' R2", "(U2) R' U R U R' U' R' D' R U' R' D R2", "M U' M' F R U R' U' F' M U M'", "(U') F R U R' U' R U R' U' F' U' R' F' U' F U R", "F R U' R' U' R U2 R' U' R U' R' U' R U2 R' U' F'", "(U) r' U' R' F R U r F R U' R' F'"],
    "U3": ["R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", "(U') F2 R U' R' U' R U R' F' R U R' U' R' F R F2", "R U' R' U R U' L U r' F U2 R U2 R2 x", "(U) R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R' U2 R", "(U) R U' L U L' U R' U' l U2 R U2 R2 x", "(U) R' U L' U' L U' R U l' U2 R' U2 R2 x'", "F R U R U2 R' U' R U' R' U2 R' U2 R U' R' U' F'", "(U') r U R' U' r' F R2 U' R' U' R U2 R' U' F'", "(U) F U R U2 R' U R U R2 F' r U R U' r'", "(U') R U2 R' U2 R' F R U R U2 R' U' R U2 R' U' F'", "(U') R' U' R F R2 D' R U R' D R2 U' F'", "(U') r U R' U' r' F R U R' U' R F' R' U R"],
    "U4": ["x R2 U2 R' D2 R U2 R' D2 R' x'", "(U2) x R2 D2 R U2 R' D2 R U2 l", "R U R' U R U' R' U2 R' D' R U2 R' D R2 U' R'", "(U') R' U2 R U R' U R' D R' U2 R D' R' U2 R'", "(U') R U' R' U' R U' R' U R' D' R U R' D R2 U R'", "(U') R' U R U R' U R U' R D R' U' R D' R2 U' R", "R' U2 R U R' U R' D' R U' R' D R U R", "R U' R' U' R U2 R' U2 R' D' R U' R' D R", "R' U' R U2 R' F' R U R' U' R' F R2 U2 R' U R", "(U2) R U R' U R U R' U2 R U' R2 D' R U' R' D R", "F R U' R' U R U R' U R U' R' F'", "(U) F' R U R' U' R' F R2 U R' U2 R U R' U2 R U' R'"],
    "U5": ["R2 D' r U2 r' D R U2 R", "R2 D' R U2 R' D R U2 R", "R U' R' D R' U' R D' R2 U R' U' R' U2 R'", "(U2) R U R' U R U2 R2 U z U R' D R U' z'", "(U) R2 D' R U' R' D R2 U' R' U2 R", "(U') R' U R U R' U2 R U2 y R U' R' U2 R U' R'", "(U') R2 D R' U R D' R2 U' R U' R' U2 R U' R' U2 R U R'", "(U) R U L' U R' U' L U' R U R' U R U' R'", "(U') R' U2 R2 D R' U2 R D' R2 U R U2 R' U2 R", "(U') R U R' U2 F2 R U2 R' U2 R' F2 R2 U R'", "(U') R' U2 R' D' R U2 R' D R U2 R U R' U R", "(U') R' U R U' R' U' R U2 R D R' U' R D' R2 U' R"],
    "U6": ["R' U2 R U R2 F' R U R U' R' F R", "(U2) R2 D R' U2 R D' R' U2 R'", "R' U' R U R U R' U' R' U F R U R U' R' F'", "R U' R' U' R U2 R' U' R' D' R U2 R' D R", "(U) R U R2 D' R U R' D R2 U2 R'", "(U') R U' R' U' R U2 R' U2 y' R' U R U2 R' U R", "(U) R' U R' U' D' R U' R' U2 R U' R' D R U' R", "(U) R' U' L U' R U L' U R' U' R U' R' U R", "(U') R' U' R U R' U R U2 F R' U R U' F' R' U2 R", "(U) R U R' U R U' R' U R U' R' U' L' U R U' R' L", "(U') R U2 R D R' U2 R D' R' U2 R' U' R U' R'", "(U') R U' R' U R U R' U2 R' D' R U R' D R2 U R'"],

    "L1": ["R U2 R' U2 R' U' R U R U' R' U2 R' U2 R", "R U R' U R U' R' U R U' R' U R U2 R'", "(U2) R U2 R' U' R U' R' U2 R U R' U R U2 R'", "(U2) R U R' U R U2 R' U2 R U2 R' U' R U' R'", "R2 U R' U R' U' R U' R' U' R U R U' R2", "(U') R2 U' R U' R U R' U R U R' U' R' U R2", "(U) R' U2 R U R' U R U' R U2 R' U' R U' R'", "(U2) R U2 R' U' R U' R' U R' U2 R U R' U R", "(U) R2 U R' U' R' U R U R' U R U' R U' R2", "(U2) R2 U' R U R U' R' U' R U' R' U R' U R2", "(U2) R U R' U R U2 R' U R' U' R U' R' U2 R", "(U) R' U' R U' R' U2 R U' R U R' U R U2 R'"],
    "L2": ["F R U' R' U' R U R D R' U' R D' R' U2 R' U' F'", "(U) F R U R' U' R U' R' U2 R U2 R' U' F'", "L' U2 R U' R' U2 L R U' R'", "R' U' R U R' F' R U R' U' R' F R2", "F R U R' U' R' F R2 U' R' U' R U R' F2", "R' U' R U R' U' R' F R2 U' R' U' R U R' F' U R", "(U) r U2 R r2 F R' F' r2 U2 r'", "(U2) r U2 r2 F R F' r2 R' U2 r'", "(U2) F R U R' U' F' r U r' U R U' R' r U' r'", "(U) r U r' R U R' U' r U' r' F U R U' R' F'", "(U) R U2 R' U' L' U2 R U R' L U L' U L", "(U) R U R' U' R' U2 R' U D R' U' R U2 D' R"],
    "L3": ["(U') F' r U R' U' r' F R", "R' U' R U R' F2 R U2 R' U2 R' F2 R2", "(U') F' R U2 R' U2 R' F R U R U' R'", "(U) R' U R U' R' U R U R' U' R2 D R' U R D' R'", "F R U' R' U' R U2 R' U' F'", "(U2) R' U' R U2 R' F' R U R' U' R' F R2 U R' U2 R", "R' F R U R U' R' F' U R U R' U R U' R'", "R' U R U2 R' L' U R U L U r' F r", "(U) F R' F' R U R U' R' F U R U' R' U R U' R' F'", "(U') F' R U2 R' U2 R' F U2 R U R U' R2 U2 R", "(U2) R U R' U R' D' R U2 R' D R2 U' R' U R U' R'", "(U) R' U' R' D' R U2 R' D R U R U' R' U' R"],
    "L4": ["(U2) F R' F' r U R U' r'", "(U') R U R' U' R B2 R' U2 R U2 R B2 R2", "(U2) F R U R' U' R' F' R U2 R U2 R'", "(U2) R U' R' U R U' R' U' R U R2 D' R U' R' D R", "(U) F' r' F r U r' F2 r U F", "(U) R U R' U R U R' U' R U R D R' U2 R D' R' U' R'", "(U) L R U' R' U R L' U R' U R U' R'", "(U) L U' R U R' L' U2 R U' R' U' R U' R'", "(U) R' U2 R U R' U' F' R U R' U' R' F R2 U R' U R", "(U) R' U2 R2 U R' U' R' U2 F R U R U' R' F'", "(U) R U R' U R U' R' U' L' U R U' M' x'", "(U2) R U R D R' U2 R D' R' U' R' U R U R'"],
    "L5": ["(U) R' U2 R' D' R U2 R' D R2", "(U) R' U2 R' D' r U2 r' D R2", "(U2) R D R' U2 R D' R' U' R' U2 R U' R' U' R", "(U2) R U2 R U R U' R2 D R' U R D' R U R'", "(U) R U R' U2 R U R' U2 y' R' U2 R U' R' U' R", "R' U2 R U R2 D' R U R' D R2", "(U) R U R' U' R U' R' U L' U R U' L U' R'", "(U) R U' R' U2 R U R' U2 R U R' U R2 D R' U' R D' R2", "(U) R' U2 R U2 R' U' R2 D R' U2 R D' R2 U2 R", "(U2) F' R U R' U' R' F R2 U' R' U' R U' R' U R U R'", "R U' R2 F2 R U2 R U2 R' F2 U2 R U' R'", "(U) R' U R2 D R' U R D' R' U2 R' U R U R' U' R"],
    "L6": ["(U2) R U2 R D R' U2 R D' R2", "(U) R' F' R U R' U' R' F R2 U' R' U2 R", "(U') L' U R U' L U R2 U2 R U R' U R", "(U') F R U R' U' R' F' U' R U R U' R' U' R' U R", "(U2) R' U' R U2 R' U' R y U2 R U2 R' U R U R'", "(U') R U2 R' U' R2 D R' U' R D' R2", "(U2) R' U' R U R' U R U' L U' R' U L' U R", "(U2) R' U R' D' R U R' U2 R U R' D U R U' R", "(U2) R U2 R' U2 R U R2 D' R U2 R' D R2 U2 R'", "(U') R U R' U R U2 R D R' U2 R D' R' U2 R'", "(U') R' U R2 B2 R' U2 R' U2 R B2 U2 R' U R", "(U2) R U' R2 D' R U' R' D R U2 R U' R' U' R U R'"],

    "Pi1": ["R' U' R U R U2 R' U' R U' R2 U2 R", "R U R' U' R' U2 R U R' U R2 U2 R'", "(U') R' U2 R U R' U R2 U R' U R U2 R'", "(U) R U2 R' U' R U' R2 U' R U' R' U2 R", "(U') R U2 R' U2 R U' R' U2 R U' R' U2 R U R'", "(U) R' U2 R U2 R' U R U2 R' U R U2 R' U' R", "(U2) R U' R' U2 R U R' U2 R U R' U2 R U2 R'", "(U2) R' U R U2 R' U' R U2 R' U' R U2 R' U2 R", "R' U2 R2 U R2 U R2 U2 R'", "R U2 R2 U' R2 U' R2 U2 R", "R U R' U' R' U' R U R U R' U' R' U R U' R U' R'", "R U2 R' U' R U' R' U' R U2 R' U' R U' R'"],
    "Pi2": ["F R2 U' R U' R U' R' U2 R' U R2 F'", "(U2) F R2 U' R U2 R U R' U R' U R2 F'", "F U R' U' R2 U' R2 U2 R U2 R U R' F'", "r' U' R U' R' U R U' R' U R' F R F' U r", "(U) R U2 R' U' F' R U2 R' U' R U' R' F R U' R'", "(U) R' U' R' D' R U R' D R U2 R' D' R U2 R' D R2", "(U') R' U' R U R' U' R2 D R' U R D' R' U R' U2 R", "(U) R U R' U' R U R2 D' R U' R' D R U' R U2 R'", "(U2) R U2 R' U R' D' R U R' D R2 U' R' U R U' R'", "(U2) R' U2 R U' R D R' U' R D' R2 U R U' R' U R", "R2 D R' U' R D' R' U' R' U R U' R' U' R U' R'", "R2 D' R U R' D R U R U' R' U R U R' U R"],
    "Pi3": ["(U') F U R U2 R' U R U R' F' R U2 R' U' R U' R'", "r U' r' U' r U r' U' l R U' R' U l'", "r' U r U r' U' r U R2 F R F' R", "r' U' R U' R' U2 r U' R U2 R' U2 R' F R F'", "R' U' R U R2 F' R U R U' R' F U' R U R' U R.", "R U2 R D' R U' R' D R' U' R2 U2 R", "R' U' R U' R2 D' R U R' D R2 U' R' U2 R", "(U2) L' U R U' L U' R' U' R U' R'", "R U' L' U R' U L U L' U L", "(U) R2 D' R U2 R' D R2 U R2 D' R U R' D R2", "(U') R2 D R' U2 R D' R2 U' R2 D R' U' R D' R2", "(U2) R U2 R' U' R U r' F2 r U2 R' U' r' F r"],
    "Pi4": ["(U) R U2 R2 U' R U' R' U2 F R U R U' R' F'", "(U') R U R' U R U2 R2 F' r U R U' r' F", "(U') r' F' r U' r' F2 r2 U R' U' r' F R F'", "F R U R' U' R' F' R U2 R' U' R2 U' R2 U2 R", "(U) R' U' R L U2 R' U2 R U2 L' U R' U2 R", "(U') F U' R U' R' U R U R' U2 R U2 R' U F' U", "(U) R2 D' R U' R' D R U R' D' R U R' D R U R U' R' U' R", "R' U' F' R U R' U' R' F R2 U2' R' U2 R", "(U') R U R' U R U' R' U' R' F' R U2 R U2' R' F", "(U2) R' U' R' D' R U R' D R' U R' U R U2 R'", "(U2) R U R D R' U' R D' R U' R U' R' U2 R", "(U) F U R U' R' U R U2 R' U' R U R' F'"],
    "Pi5": ["r' F' r U r U2 r' F2 U' R U R' U' R U' R'", "(U2) R U2 R' U2 R' F R2 U' R' U2 R U2 R' U' F'", "R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R", "R' L U2 R2 U R2 U R U L' U' R U2 R'", "l U2 l' U2 R' U2 R B2 U R' U R", "(U') R U R' U F2 R U2 R' U2 R' F2 R", "(U') R' U2 R U R' U R2 U' L' U R' U' L", "(U) R U R' U R U' R' U R U' R D R' U' R D' R2", "R U R' U' R' F R2 U R' U' R U R' U' F'", "(U2) R' U' R U' R' U' R U' x' U L' U L U2 R U' R' U x", "R U2 R' U' R U R' U2 L' U R U' M' x'", "(U') L R' U' R U L' U2 R' U R U' R' U2 R"],
    "Pi6": ["(U') R U R' U R U' R' U F2 r U2 r' U' r' F r", "(U) F U R U2 R' U2 R U R2 F' R U2 R U2 R'", "R U' R' U' R U' R' U R U R' U R' F' R U R U' R' F", "R L' U2 R2 U' R2 U' R' U' L U R' U2 R", "R' F2 R U2 R U2 R' F2 U' R U' R'", "(U) R' U' R U' B2 R' U2 R U2 l U2 l'", "(U) R U2 R' U' R U' R2 U L U' R U L'", "(U') R' U' R U' R' U R U' R' U R' D' R U R' D R2", "(U) F U R U' R' U R U' R2 F' R U R U' R'", "R U R' U R U2 R' U' R L' U R' U' L U2 R U2 R'", "R' U2 R U R' U' R U2 L U' R' U R L'", "(U) R L' U R' U' L U2 R U' R' U R U2 R'"],

    "H1": ["R U2 R' U' R U' R' U' R' U' R U' R' U2 R", "R' U2 R U R' U R U R U R' U R U2 R'", "(U) R' U' R U' R' U R U' R' U2 R", "(U') R U R' U R U' R' U R U2 R'", "R' U2 R U R' U' R U R' U R", "R U2 R' U' R U R' U' R U' R'", "(U) R U R' U R U' R' U R U' R' U R' U' R2 U' R' U R' U R", "(U) R U R' U R U2 R' U' R' U2 R U R' U R"],
    "H2": ["(U) x' U' R U' R' U R' F2 R U' R U R' U x", "F U R U' R' U R U' R' U R U' R' F'", "R U R' y' U R' U R U' R2 F R F' R", "R' U' R y U' R U' R' U R l U' R' U l'", "F R U R' U' R U R' U' F' U R' F' U' F U R", "R' U' R U' R' U2 R U R' U' R U R' F' R U R' U' R' F R2", "(U) L' U L U' L' U' L U R' U' R U L' U' L U2 R' U' R", "(U) R U' R' U R U R' U' L U L' U' R U R' U2 L U L'"],
    "H3": ["(U2) R U R' U R U2 R' F R U' R' U' R U2 R' U' F'", "l U' R U R' l' U r U' r' U r U r'", "(U2) R' F R' F' R2 U' r' U r U' r' U' r", "(U) R' U' R U' R' U' L U' R U L'", "(U) R U R' U R U L' U R' U' L", "(U') R' U' R U' R U R2 U R2 U L' U R' U' L", "(U') R U R' U R' U' R2 U' R2 U' L U' R U L'", "R U2 R2 U' R' D R' U' R D' R U2 R", "R U2 R' U' R2 D R' U R D' R2' U' R U' R'", "(U2) R U R' U' L' U2 R U2 R' U L U' r' F2 r", "(U') R2 D' R U' R' D R2 U' R2 D' R U2 R' D R2", "(U') R2 D R' U R D' R2' U R2 D R' U2 R D' R2'"],
    "H4": ["(U2) F R' F' r U R U' r2 F2 r U r' F r", "(U) R U R' U' R' F R U R U' R' F' R U R' U R U2 R'", "R' U2 R U' L U2 R' U2 R U2 L' R' U R", "R U2 R' U L' U2 R U2 R' U2 L R U' R'", "(U') F U' R U2 R' U2 R U' R' U' R U R' U F'", "(U') R' F R U R' U' F' R U' R' U R' F R F' U R", "(U') R U2 R' U' R U' R D' R U' R' D R U R", "R U2 R2 F U' R2 U' R2 U F' U R", "(U2) R' U2 R U2' R2 F' R U R U' R' F U R", "(U') F B' R2 B R2 U' R2 U' R2 U R2 F'", "(U2) F R U R' U' R' F' U2 R U R' U R2 U2 R'", "(U) F R U' R' U R U2 R' U' R U R' U' F'"],

    "S1": ["(U') R' U R2 U R' U R U2 R U2 R U R' U R2", "(U') R' U2 R2 U R  U' R' U R U R2 U' R'", "R U R' U R U2 R'", "(U') R' U2 R U R' U R", "R U R2 U' R2 U' R2 U2 R2 U2 R'", "(U2) R' U' R U' R U R2 U R2 U2 R'", "(U') R U R' U' R' U2 R U R U' R' U R' U R", "(U') R' U' R U R U R' U' R' U R U R U' R'", "R U R' U R U' R' U R' U' R2 U' R' U R' U R", "R U R' U R U R U R U R U' R' U' R2", "(U) R U R' U R' U' R2 U' R' U R' U' R U R' U R", "R U R' U R U' R' U R' U' R' U R U' R' U' R2 U R"],
    "S2": ["F U' R' U R U F' R U R2 U R2 U2 R'", "(U) R' D' R U' R' D R U2 R U R' U2 R U R'", "R' U2 R U R' U' R F U' R' U' R U F'", "R' U R U2 R' U R U2 R D R' U' R D' R'", "L' U2 R U' R' U2 L U R U' R' U R U2 R'", "(U) F R U R' U' R U R2 U' F' U R U R U' R'", "(U2) R U R' F' R U R' U R U2 R' F R U' R'", "(U) R U2 L' R' U2 R U2 R' U2 L U' R U' R'", "(U') R U' R2 U2 D' R U R' U D R2 U R'", "(U) F U R' F R F' R U' R' U R U' R' F'", "R U R' U' L' U R U' L U' L' U R' U' L", "(U2) r' F2 R F' r U' R' U r' F r U2 R U2 R'"],
    "S3": ["R U' L' U R' U' L", "(U) R' U2 R U R' U' R' D' R U2 R' D R2", "(U') R' D U' R' U R U2 D' R2 U R' U' R'", "(U) R' U' R' U R2 D' U2 R U R' U' D R'", "R2 D R' U2 R D' R' U' R' U R U2 R'", "D' R U R' U R U' R' U' D R2 U' R U' R' U R' U R2", "R U R' U R U R' U' R U R D R' U' R D' R' U2 R'", "(U') R' U2 R U R' U' R' D' R U' R' D R U R U' R' U' R", "(U') R' U2 F' R U R' U' R' F R U2 R", "R2 U R U R' U' R' U' R' L' U R' U' L", "(U) R U2 R' U2 R' F R2 U R' U' R U R' U' F'", "R U R' U R U' R' U' R' F R2 U' R' U' R U R' F'"],
    "S4": ["R' D R2 D' R2 U R2 D R2 D' R2 U' R'", "(U') R U R' U R U' R D R' U' R D' R2", "(U2) R U' R' U' R U' R' U2 R U R2 D' R U2 R' D R", "(U) F U R U' R' U R U' l U' R2 D' R U R' x", "(U2) R2 D' R U' R' D R U' R U R' U R", "(U) R U2 R' L' U2 R U R' U2 L R U2 R'", "R' D' R U R' D R2 U' R' U R U R' U' R U2 R' U R U2 R'", "R U' R' U' R U R D R' U2 R D' R2 U R U2 R'", "(U') R' U2 R' D' R U R' D R U' R U R' U R", "(U) R' U' R U' R2 F' R U R U' R' F U2 R", "(U2) R U R' U R' D' R U R' D R U' R U2 R'", "(U2) R U2 R' U' R U R' U' R U R D R' U2 R D' R2"],
    "S5": ["f R' F' R U2 R U2 R' U2 S'", "(U) R' D' R U R' D R2 U R' U2 R U R'", "R' D R' U R D' U R U' R' U' R2 U R U' R'", "(U) R' U2 R U R2 D' R U' R' D R U2 R", "(U2) R2 D' r U2 r' D R2 U R' U R", "R' U2 R U R' U R' D' R U2 R' D R U2 R", "R L' U R' U' L U2 R U2 R'", "(U2) R2 D' R U2 R' D R2 U R' U R", "R2 F R U R U' R' F' R U' R' U R", "(U) R U R' U R' U' R' D' R U R' D R' U2 R'", "(U') R' U' F U' R2 U R2 U F' R U' R U' R'", "(U') R' U' R' D' R U' R' D R' U R2 U R U' R U' R'"],
    "S6": ["(U2) R U R' U' R U R2 D' R U2 R' D R2 U2 R'", "R U R' U R U' R2 F' R U R U' R' F R U' R'", "(U2) R U R' U R2 D r' U2 r D' R2", "R' U R U2 R' U R2 D R' U R D' R'", "(U') R' U' R U R2 U' R' U' R U D' R U R' D R'", "(U2) R U R' U R2 D R' U2 R D' R2", "(U2) R' U2 R U2 L U' R' U L' R", "R U2 R D R' U2 R D' R' U R' U R U2 R'", "R U R2 F' R U2 R U2 R' F R U' R'", "(U) R U R' U' R U R2 D' R U R' D R U R U2 R'", "F' R U R' U R U2 R' F U R U' R' U2 R U' R'", "(U) R' F R U R' U' R' F' D' R U R' D R2"],

    "AS1": ["(U) R U' R2 U' R U' R' U2 R' U2 R' U' R U' R2", "(U) R U2 R2 U' R' U R U' R' U' R2 U R", "R' U' R U' R' U2 R", "(U) R U2 R' U' R U' R'", "R' U' R2 U R2 U R2 U2 R2 U2 R", "(U2) R U R' U R' U' R2 U' R2 U2 R", "(U) R' U' R U R U2 R' U' R' U R U' R U' R'", "(U) R U R' U' R' U' R U R U' R' U' R' U R", "(U) R U R' U R' U' R U R' U' R2 U' R2 U R U' R' U R", "R' U' R U' R' U' R' U' R' U' R' U R U R2", "(U) R U R' U' R U R2 U' R2 U' R' U R U' R' U R' U R", "(U2) R U R' U R' U' R' U R U' R' U' R' U' R' U2 R"],
    "AS2": ["(U') R U2 R2 U' R2 U' R' F U' R' U' R U F'", "(U') R D R' U R D' R' U2 R' U' R U2 R' U' R", "(U') R U2 R' U' R U R' L' U R U' L U2 R'", "R U' R' U2 R U' R' U2 R' D' R U R' D R", "(U') F U' R' U R U F' R' U R U' R' U2 R", "(U) R U R' U L' U2 R U2 R' U2 R L U2 R'", "R U R' F' R U2 R' U' R U' R' F R U' R'", "R U  R' U' R' U' F U R2 U' R' U R U' R' F'", "(U) R' U R2 U2 D R' U' R U' D' R2 U' R", "R' U R U R' U r U' R' U R U r' R' F R F' U R", "z D' R' D R U R' D' R U' R U R' D R U' z'", "R U2 R' U' R U r' F r U2 R' U' r' F2 r"],
    "AS3": ["R' U L U' R U L'", "(U') R U2 R' U' R U R D R' U2 R D' R2", "(U) R D' U R U' R' U2 D R2 U' R U R", "(U') R U R U' R2 D U2 R' U' R U D' R", "R2 D' R U2 R' D R U R U' R' U2 R", "D R' U' R U' R' U R U D' R2 U R' U R U' R U' R2", "R' U' R U' R' U' R U R' U' R' D' R U R' D R U2 R", "(U) R U2 R' U' R U R D  R' U R D' R' U' R' U R U R'", "(U2) F U R U' R' U R U' R2 F' R U2 R U2 R'", "(U2) F R U' R' U R U R2 F' R U R U R' U' R U' R'", "(U2) R' U2 R' F' R U R U' R' F U2 R", "(U2) L' U R U' L R U R U R U' R' U' R2"],
    "AS4": ["R D' R2 D R2 U' R2 D' R2 D R2 U R", "(U) R' U' R U' R' U R' D' R U R' D R2", "l U' R' D R2 U l' U R' U' R U R' U' F'", "(U') R' D' R U2 R' D R2 U' R' U2 R U R' U R U R'", "(U2) R2 D R' U R D' R' U R' U' R U' R'", "(U) R U2 R' L' U2 R U' R' U2 L R U2 R'", "(U') R U R' U' R' U' R U R U' R' U' R2 D' R U' R' D R U2 R", "(U') R U2 R' U' R2 D R' U2 R D' R' U' R' U R U R'", "(U) R U2 R' U R' D' R U' R' D R U' R U' R'", "(U') R2 D R' U2 R D' R' U' R' U R U' R' U  R U2 R'", "(U2) R' U' R U' R D R' U' R D' R' U R' U2 R", "(U2) R' U2 F' R U R' U' R' F R2 U R' U R"],
    "AS5": ["(U') R U2 R2 D' R U2 R' D R2 U' R' U R U' R'", "(U') R D R' U' R D' R2 U' R U2 R' U' R", "R D' R U' R' D U' R' U R U R2 U' R' U R", "R U R' F' R U R' U' R' F R2 U R' U' R U' R'", "(U2) R2 D r' U2 r D' R2 U' R U' R'", "R U2 R' U' R U' R D R' U2 R D' R' U2 R'", "L R' U' R U L' U2 R' U2 R", "(U2) R2 D R' U2 R D' R2 U' R U' R'", "R U R' F' R U2 R' U2 R' F R2 U' R'", "(U') R' U' R U' R U R D R' U' R D' R U2 R", "(U) R U R' U2 R U R' U' F' R U2 R' U' R U' R' F", "R2 D' R U' R' D F R U R U' R' F' R"],
    "AS6": ["(U') R U2 R' U' F' R U R' U' R' F R2 U' R'", "(U') R' U2 R' D' R U R' D R2 U' R' U2 R", "(U2) R' U' R U' R2 D' r U2 r' D R2", "R U' R' U2 R U' R2 D' R U' R' D R", "(U) R U R' U' R2 U R U R' U' D R' U' R D' R", "(U2) R' U' R U' R2 D' R U2 R' D R2", "(U2) R U2 R' U2 L' U R U' R' L", "R' U2 R' D' R U2 R' D R U' R U' R' U2 R", "R' U' R U R' F R U R' U' R' F' R2", "(U) R U2 R D' R U' R' D R U R U' R U' R'", "(U) R U R' U R' F U' R2 U' R2 U F' U R", "(U') R U R' U R' U' R2 U' R D' R U R' D R U R"],

    //"sune cases where you can't just mirror the antisune case in your head (24 algs)": ["F R U R' U' R U R2 U' F' U R U R U' R' ", "F U R' F R F' R U' R' U R U' R' F'", "R' U2 R U R' U' R F U' R' U' R U F'", "L' U2 R U' R' U2 L U R U' R' U R U2 R'", "R U R' F' R U R' U R U2 R' F R U' R'", "R U2 L' R' U2 R U2 R' U2 L U' R U' R'", "R2 U R U R' U' R' U' R' L' U R' U' L", "R' U2 F' R U R' U' R' F R U2 R U", "R U2 R' U2 R' F R2 U R' U' R U R' U' F'", "R U' R' U' R U R D R' U2 R D' R2 U R U2 R' U", "R' U2 R' D' R U R' D R U' R U R' U R", "R' U' R U' R2 F' R U R U' R' F U2 R", "R U2 R' L' U2 R U R' U2 L R U2 R'", "U R U2 R' U' R U R' U' R U R D R' U2 R D' R2", "R' D' R U R' D R2 U' R' U R U R' U' R U2 R' U R U2 R'", "(U') R U2 R2 D' R U2 R' D R2 U' R' U R U' R' ", "R U R' F' R U R' U' R' F R2 U R' U' R U' R'", "R U R' F' R U2 R' U2 R' F R2 U' R'", "(U) R U R' U R' U' R' D R' U' R D' R U2 R", "R2 D' R U' R' D F R U R U' R' F' R ", "R U R' U R U' R2' F' R U R U' R' F R U' R'", "R U R2 F' R U2 R U2 R' F R U' R'", "(U) R U R' U' R U R2 D' R U R' D R U R U2 R'", "(U') R' U2 R' D R' U R D' R U R U' R U' R'", "(U) R' F R U R' U' R' F' D' R U R' D R2"],

}

var ollcp = {
	
	"1":[ "r U R' U R' r2 U' R' U R' r2 U2' r'", "R U2' R2' F R F' U2 R' F R F'", "R U' R2 D' r U' r' D R2 U R'", "F R U R' U' F' r' U r2 U' r2' U' r2 U r'",  ],
	"2":[ "F R U R' U' F' f R U R' U' f'", "R2 F2 r U2 R U' r2 F2 r F R", "r U R' U2 R U2 r2 F2 r F' r' F2 r", "R' F' r' F2 r2 U R' U2 r' F2 R2", "U' R U' R2' D' r U r' D R2 U R'", "r D' R2' U' R U2 R' U R2 D r'",  ],
	"3":[ "U' f R U R' U' f' U' F R U R' U' F'", "U' F' r U R' U r' F2 R U2 R' F R", "f U R U' R' f' F R' F' R U R U' R'", "U R' F2 R2 U2' R' F R U2' R2 F2 R", "U R' D' r U' r' D R U F R' F' R", "U F R U R' U' F' r' U2 R U R' U r",  ],
	"4":[ "U f R U R' U' f' U F R U R' U' F'", "U r U2 r2 F2 r F' R U2 R2 F2 R", "U' R' F' R U2 R' F2 r U' R U' r' F", "U' F R' F' r U' R U2 r' U2 r U' r'", "U' R D r' U r D' R' d' R' F R F", "R' F' U' F U R U' r U2 R' U' R U' r'",  ],
	"5":[ "U' r' U2 R U R' U r", "U' r D' R2 U' R U R' U R2 D r'", "R' F' R U R' U' R' F R F' U F R", "U F U' R2 D R' U R D' R2 U F'", "U2 R U' R' U' F' U R U R' U' R' F R", "r' U2 R U R' U F' U' F U r",  ],
	"6":[ "U r U2 R' U' R U' r'", "U F U' R2 D R' U' R D' R2 U F'", "U F R U' R' U R U2 R' U' F'", "U r' D R2 U R' U' R U' R2 D' r", "R' F R F' U' r' D' r U r' D r", "r U2 R' F R' F' R U' R U' r'",  ],
	"7":[ "r U R' U R U2 r'", "L' U2 L U2 L F' L' F", "F R' F' R U2 R U2 R'", "U2 R' U2 R U R' U R2 U R' U' R' F R F'", "R U' R' U' F' U2' F U2' R U2 R'", "U R' U' F R' F' R U' R U R' U R",  ],
	"8":[ "r' U' R U' R' U2 r", "U F R' F' R U R U' R2 U' R U' R' U2 R", "f' U f R' U2 R' U2 R", "U2 R U2 R' U2 R' F R F'", "U' R U2 R' U2' F' U2' F U R U R'", "R U2 R' F R' F' R U' R U' R'",  ],
	"9":[ "U M R U2 R' U' R U' R' U' M'", "F2 r U r' U2 F R U2 l U' R' U l' ", "U' F R U R' U' R U' R' U R U2 R' U' F'", "U2 R U R' U' R' F R2 U R' U' F'", "U' F' U' F r U' r' U r U r'", "U' R' U' R U' R' U R' F R F' U R",  ],
	"10":[ "U2 M U R' U2 R U R' U R U M'", "L' U' L U L F' L2 U' L U F", "U2 R' U' R U F R U R' U' F' R' U R", "r' U' F2 R U' R' U2 r' F r U' r", "U2 R U R' y R' F R U' R' F' R", "U2 R U R' U R' F R F' R U2 R'",],
	"11":["r' R2 U R' U R U2 R' U M'","U2 r U R' U R2 D R' U2 R D' R' r'","f U R U' R2 F' R U R U' R' S'","U r' U' R U' R' U2 x U R U' L U R'","R2 D r' U' r D' R' U2 R' F' U F","U2 r U R' U R' F R F' R U2 r'",],
	"12":["r R2' U' R U' R' U2 R U' M","U' l U L' U L U2 x U' L' U R' U' L","R2 D' r U r' F r U r' F2 D R2","U F R U' R' F2 u' r U r' D R","R2 D' r U r' D R U2 R y R U' R'","l' U' L U' L F' L' F L' U2 l",],
	"13":["U2 R' U' R U' r U R2 U R2 U2 r'","F U R U2 R' U' R U R' F'","F U R U' R2' F' R U R U' R'","U R' U' R U' R' U R y r U' r' U r U r'","r U' r' U' r U r' F' U F","U2 F U R U' R2 F2 R U2 R U2 R' F",],
	"14":["U2 R U R' U r' U' R2 U' R2' U2' r","U' R U R' U R U' R' y R' F R U' R' F' R","U2 F' U' r' F r2 U r' U' r' F r","U2 F' U' L' U2 L U L' U' L F","r' U r U r' U' r y R U' R'","U' R U2 R' U' R U R2 F R F' R U2 R'",],
	"15":["U' r' U' r R' U' R U r' U r","U2 R' U2 R U R' F U R U' R' F' R","U' L F' L' U' L U F L' U L U2 L'","U' l' U l U l' U' l y' R U R' U' R U' R'","U R U2 R' U' R U R' U' R U R' U2 R' F R F'","U F R U R' U' F' R' U2 R U R' U R",],
	"16":["U r U r' R U R' U' r U' r'","U' r U' r' U' r U r' y' R' U' R U R' U R","U' R' F R U R' U' F' R U' R' U2 R","L U2 L' U' L F' U' L' U L F L'","U F R U R' U' F' U R U' L' U R' U' L","U' F R U R' U' F' R U2 R' U' R U' R'",],
	

}

var algdbOLLCP = {
"1": ["r U R' U R' r2 U' R' U R' r2 U2' r' /U r' U2' r2 R' U R' U' r2 R' U R' U r / r' U' R U' r2' R U R U' r2' R U2 r /U r U2 R r2' U' R U R r2' U' R U' r'","R U2' R2' F R F' U2 R' F R F' / r U2' R2' U' R U' r' U2' F R F' / l' U2 L2 U L' U l U2 F' L' F / R U B' R B R2 U' R' F R F'","U' R U' R2 D' r U' r' D R2 U R' /U R' U R2 D r' U r D' R2' U' R","U2 R U2 R2' F R F' U2 R' F R F' /U2 l' U2 L2 U L' U l U2 F' L' F /U2 R U B' R B R2 U' R' F R F' /U2 r U2' R2' U' R U' r' U2' F R F'","U' R' U R2 D r' U r D' R2' U' R /U R U' R2 D' r U' r' D R2 U R'","U F R U R' U' F' r' U r2 U' r2' U' r2 U r'",],
"2": ["F R U R' U' S R U R' U' f' / F R U R' U' F' f R U R' U' f' / F R U r' U' R U R' M' U' F' /U r U r' U2 R U2 R' U2 r U' r'","U2 R U R' U F' U2' F R U' R2' F R F' / F' L F L2' U' L F U2 F' U L' U L","F R' F' U2 r U R' U R2 U2 r' /U2 F' L F U2 l' U' L U' L2 U2 l","L' U' L U' F U2 F' L' U L2 F' L' F /U2 F R' F' R2 U R' F' U2 F U' R U' R'","U R' U R2 D r' U' r D' R2' U' R /U' R U' R2' D' r U r' D R2 U R'","U f R U R' y' r' R U R' U' r U' r' / r D' R2' U' R U2 R' U R2 D r' /U' F R U R' U' F' l U L' U L U2 l'",],
"3": ["M U l' U2 l U L' U L M' /U' f R U R' U' f' U' F R U R' U' F' / r' R2 U R' U r U2 r' U M' / r' R U R' F2 R U L' U L M'","U' F' r U R' U r' F2 R U2 R' F R","U' L F L' U2 L F2 l' U L' U l F'","U R' F2 R2 U2' R' F R U2' R2 F2 R /U L U L' U' r U2' R' U' R2 B2 R' U' r'","U' F U F' l' U' M U2 L U' l' U' l","U F R U R' U' F' r' U2 R U R' U r",],
"4": ["U2 M U' r U2' r' U' R U' R' M' /U f R U R' U' f' U F R U R' U' F' /U' F U R U' R' F' U' F R U R' U' F' /U2 l L' U' L F2' L' U' R U' R' M'","U L F2' L2' U2 L F' L' U2 L2 F2' L' /U R' U' R U l' U2 L U L2 B2' L U l","U' R' F' R U2 R' F2 r U' R U' r' F /U R' F R F' U2 R B L U2 L' B' R","U' F l' U' L U' l F2 L' U2 L F' L' /U R' F' L' U2 L F R U2 B' R B R' /U R' F' r' F2 r F R U2 y R' F R F'","U' R D r' U r D' R' U' B' R B R' /U' F' U' F r U M U2 R' U r U r' /U' R D r' U r D' R' d' R' F R F'","U F' L' U' L U F l U2 L' U' L U' l'",],
"5": ["U' r' U2 R U R' U r /U l' U2 L U L' U l /U' L' U' L2 F' L' F2 U' F' /U R' F2 r U r' F R","U' r D' R2 U' R U R' U R2 D r'","U F' L' U L U' L' U2 L U F","U F U' R2 D R' U R D' R2 U F'","L F' L' F l' U' l U2 M' U' M","r' U2 R B' R B R' U R' U r / r' U2 l U' R U l' U R' U r",],
"6": ["U r U2 R' U' R U' r' /U' l U2 L' U' L U' l' /U' R U R2 F R F2 U F / x' D R2 U' R' U R' D' x","U F U' R2 D R' U' R D' R2 U F' / R' F R F' U r' D' r U' r' D r","U F R U' R' U R U2 R' U' F'","U r' D R2 U R' U' R U' R2 D' r","R' F R F' U' r' D' r U r' D r /U2 R' F R F' r U r' U2 M' U M","r U2 R' F R' F' R U' R U' r' /U2 l U2 L' B L' B' L U' L U' l'",],
"7": ["r U R' U R U2 r' /U2 l U L' U L U2 l'","L' U2 L U2 L F' L' F","F R' F' R U2 R U2 R'","U2 R' U2 R U R' U R2 U R' U' R' F R F' /U' r U' L U L' U2 R' U' l U2 F' L'","R U' R' U' F' U2' F U2' R U2 R' /U' M' U' M U2 r U' r' F R' F' R / R U R' U' R' F R U R U2 R' U' R U R' F' /U R' U2 R U2 F R2 U R2 U' R U R U' F'","U R' U' F R' F' R U' R U R' U R / R' U2 R U R' U F' U' F U R /U' L' U' B L' B' L U' L U L' U L / x' R' F2 R U' R U R' x U R' U R",],
"8": ["r' U' R U' R' U2 r /U2 l' U' L U' L' U2 l /U2 R' F' r U' r' F2 R","U' l' U R' U' R U2 L U r' U2 F R","U2 F' L F L' U2 L' U2 L / f' U f R' U2 R' U2 R","U2 R U2 R' U2 R' F R F' / L U2 L' U2 L' f U f'","U' M' U M U2 l' U l F' L F L' /U' R U2 R' U2' F' U2' F U R U R'","R U2 R' F R' F' R U' R U' R' /U' R U B' R B R' U R' U' R U' R' /U' f R U R' U' f' R U2 R' U' R U' R'",],
"9": ["U M R U2 R' U' R U' R' U' M' /U R U2 R' M' U' R U' R' U M /U r' R2 U2 R' U' R U' R' U' M' /U2 M' U' R U2 R' U' R U' R' U' M","U2 R B U2 r' U L U2 R U' R' U l'","U' F R U R' U' R U' R' U R U2 R' U' F' /U2 l' U2 L U' R U2 r' F U' R U' R'","U2 R U R' U' R' F R2 U R' U' F'","U2 R' U' R y r U' r' U r U r' /U' F' U' F r U' r' U r U r' /U2 F R' F' R U2 R U' R' U R U' R' U R U2 R' /U2 R' U' R y' x' R U' R' F R U l'","U' R' U' R U' R' U R' F R F' U R / L' U' L U' L F' L' F L' U2 L /U2 R' U' R U' R B' R' B R' U2 R /U f' L' U' L U f U' L' U' L U' L' U2 L",],
"10": ["U M L' U2 L U L' U L U M' /U' r R2' U2 R U R' U R U r' R /U2 M U R' U2 R U R' U R U M' / r U R' U R U' R' U' r' R U R U' R'","L' U' L U L F' L2' U' L U F /U2 R' U' R U R U R' U' R' F R F' R' U R /U R U' R' F' U F R U R' U2 R U2' R /U2 R' U' R U F R U R' U' F' R' U R","U' F' L' U' L U L' U L U' L' U2 L U F / r U2 R' U L' U2 l F' U L' U L /U2 R' U' R U F R U R' U' F' R' U R /U2 F R U R D R2' U' R U R2' D' R U' F'","r' U' F2 R U' R' U2 r' F r U' r / L' B' U2 l U' R' U2 L' U L U' r /U' r U R' U R U' R D R' U' R D' R' r' /U' R2' D' R U2 R' D R2 U R' F' U F R","U2 R U R' y' r' U r U' r' U' r /U' F U F' R' F R U' R' F' R /U2 R U R' y R' F R U' R' F' R / F' L F L' U2 L' U L U' L' U L U' L' U2 L","U2 R U R' U R' F R F' R U2 R' /U' L U L' U L U' L F' L' F U' L' /U' z U R U' R U R' U F' U' F R' U /U' F U R U' R' d R' U R U2 R'",],
"11": ["M R U R' U R U2 R' U M' / r' R2 U R' U R U2 R' U M' /U F' L' U' L U F U' F' L' U' L U F /U F' L' U' L U F U F R U R' U' F'","r' U' F2 R U L' U2 R' U' L U' r /U2 r U R' U R2 D R' U2 R D' R' r' /U F' L' U L F2 u l' U' l D' L'","L F' L F' l' U2 L' U l U2 F' L' / f U R U' R2 F' R U R U' R' S'","x' D' F2 R U R' D R U' R U' R' U R' x","R2 D r' U' r D' R' U2 R' F' U F","U2 r U R' U R' F R F' R U2 r' / l U L' U r' U L U' r U2 l' /U F R U R' U' R B' R B R2 F' /U F R U R' U' F' U r U R' U R U2 r'",],
"12": ["M' R' U' R U' R' U2 R U' M / r R2' U' R U' R' U2 R U' R r' /U F R U R' U' F' U F R U R' U' F' /U2 l L2' U' L U' L' U2 L U' M'","x D B2 R' U' R D' R' U R' U R U' R x'","R2' D' r U r' F r U r' F2 D R2 /U2 R' F R' F r U2 R U' r' U2 F R","U F R U' R' F2 u' r U r' D R /U2 r' U' R U' R2' D' R U2 R' D R r","R2' D' r U r' D R U2 R y R U' R'","l' U' L U' L F' L' F L' U2 l",],
"13": ["L' U' L U' l U L2 U L2 U2 l'","F U R U2 R' U' R U R' F' /U2 f R U R2 U' R' U R U' f'","F U R U' R2' F' R U R U' R'","U R' U' R U' R' U R y r U' r' U r U r'","r U' r' U' r U r' F' U F / r U' r' U' r U r' y' R' U R","R' U2 R U R' U R U' f R U R' U' f' /U' L' U2 L U L' U' L2 F' L' F L' U2 L /U2 l U' R' F' R U R' x y R' U R / R' U2 R U R' U R2 y U R U' R' F'",],
"14": ["U2 R U R' U r' U' R2 U' R2' U2' r","U' R U R' U R U' R' y R' F R U' R' F' R /U L U L' U L U' L' y' l' U l U' l' U' l","U2 F' U' L' U L2 F L' U' L' U L /U2 F' U' r' F r2 U r' U' r' F r /U2 R U2 R' U2' R U' R' F' U' F R U R'","U2 F' U' L' U2 L U L' U' L F / f L' U' L2 U L U' L' U f /U R' U' R F U R U' R' F' U' R' U R / B' U' R' U2 R U R' U' R B","r' U r U r' U' r y R U' R' /U2 l' U l U l' U' l F U' F' /U2 R' F R U R' F' R y' R U' R'","R U2 R' U' R U' R' U F' U' r' F r F /U' R U2 R' U' R U R2 F R F' R U2 R'",],
"15": ["U' r' U' r R' U' R U r' U r /U' r' U' M' U' R U r' U r /U l' U' l L' U' L U l' U l","U' r U r' U' L U r U2 r' F U' L' /U2 R U R' U l' U2 L U' R U2 r' F /U2 R' U2 R U R' F U R U' R' F' R","U' L F' L' U' L U F L' U L U2 L'","U' l' U l U l' U' l y' R U R' U' R U' R'","U' L' R U R' U' L y' r' U' R U M' /U R U2 R' U' R U R' U' R U R' U2 R' F R F'","U' F' L' U' L U F L' U2 L U L' U L /U f' U' L' U L f R' U2 R U R' U R",],
"16": ["U r U r' R U R' U' r U' r' /U R U R' U' R' U' R U R U' r' U' R' U r /U r U M U R' U' r U' r' /U' l U l' L U L' U' l U' l'","U' r U' r' U' r U r' y' R' U' R U R' U R","U' R' F R U R' U' F' R U' R' U2 R","L U2 L' U' L F' U' L' U L F L' / l' U' l U R' U' l' U2 l F' U R /U' L' U' L U' r U2 R' U L' U2 l F'","U' R L' U' L U R' y' r U R' U' M /U L' U2 L U L' U' L U L' U' L U2 L F' L' F","U' F R U R' U' F' R U2 R' U' R U' R'",],
"17": ["U F' R U2 r' U F2 U' r U2 R' F /U' R U2 r' U' R U M' R' F2 r U r' F /U' R U2 r' U' R U r R2' F2 r U r' F","l' U l F' U2 F' U L' U L F /U2 L' U' L U' L F' L' F U2 L F' L' F /U' F U R U' R' F' U F R U' R' U R U R' F'","U R U R' U R' F R F' U2 R' F R F' /U' r U' r' F U2' F U' R U' R' F' / f R U R' U' y x U R' U' R' F R F' /U' r U' r' F U2 F U' R U' R' F'","U' F R' F' R2 r' U R U' R' U' M' /U f R U R' U' f' U' R U R' U' R' F R F'","F' L F L2' l U' L' U L U M' / F' r U r' U' S r' F r S' /U2 F U R U' R' U' R' F R F' R U R' F'","U M' U' l L2' U2 L2 F' L' F l' U2 l /U' r' R U' r R2' U2 R2 x' U' R' U L' U2 r",],
"18": ["U2 r U R' U R U2 r2 U' R U' R' U2 r / r' U' R U' R' U2 r2 U R' U R U2 r'","R U2 R' F' U2 F R U' R2 F R F' /U' R' F R U R' F' R F U' S R U R' U' f'","U2 f U R U' R f' U' R2' F R F' U' R / F R U R' d R' U2 R' F R F' /U2 F R' F' R U2 F R' F' R U' R U' R'","U2 R' F2 r U r2' F2 r U' r' F2 r F R","U2 x' U' l' U' l F' U F2 U L' U' r /U R' F R F' U2 R' F R F' U y' R' U R","U' R U2 R2 F R F' U2 M' U R U' r' / l' U' r' U2 L U2 L' U2 r U l / R U R' U R' F R F' U2 r R' U R U' r' /U x' U' R U l' U' F R' F' U R U R U' R'",],
"19": ["r U2 R' U' R U' r2 U2 R U R' U r /U2 r' U2 R U R' U r2 U2 R' U' R U' r' /U2 F R U R' U' F' R U2 R2 F R F' R U2 R'","U' F' U' F R U R D r' U' r D' R' U2 R'","U2 M U' L' U' L U M' L F' L' F /U' F R U' R' F R' F' R U R U R' U' F' /U' R' U' F U r U2 r' R U R' F' R /U' R' U' F' U F2 R U R' U' F' U R","F R U2 R' F R U R' U' R U R' U' y' R' U R' /U2 R' F' r' F2 r U r' F2 r2 U' r' F2 R /U' R U R' U F' U2' F R U' R' M' U R U' r'","U2 M U R U R' U' M' R' F R F' /U2 r' R U R U R' U' r R2' F R F' /U2 R' U2 F R U R' U' F2 U2 F R /U2 R' U2 R f U R' F R2 F' U' f'","U' R u2 R' U' R U R' F R u2 R2' F R /U2 R2' F2 R F' D R U2 R' D' F l' U2 l R",],
"20": ["r U R' U' M2 U R U' R' U' M' r' R U R U R' U' M2 U R U' r' / r' u M2 u' r U2 r' u M2 u' r / M' U M' U M' U M' U' M' U M' U M' U M'","U F R' F R2 U R' U' F2 U' L F' L' F /U' F' L F' L2' U' L U F2 U R' F R F'","F R' F R2 U R' U' F2 U' L F' L' F /U2 F' L F' L2' U' L U F2 U R' F R F' / F R' F R2 U R' U' F2 U' r U' r' F","U' F R' F R2 U R' U' F2 U' L F' L' F /U F' L F' L2' U' L U F2 U R' F R F'","U2 F R' F R2 U R' U' F2 U' L F' L' F / F' L F' L2' U' L U F2 U R' F R F' /U2 F R' F R2 U R' U' F2 U' r U' r' F","x' U R' F2 U2 R' U R2 U' R U2 F2 R U' x / F U' F' R L' U' L U R' F U' R U2 R' F' / F' U F L' R U R' U' L F' U L' U2 L F",],
"21": ["U R U2 R' U' R U R' U' R U' R' / R U R' U R U' R' U R U2 R' / R' U' R U' R' U R U' R' U2 R /U' R' U2 R U R' U' R U R' U R","F R U' R' U R U2 R' U' R U R' U' F' /U2 R' F R U R' U' R' F' R U R2 U2 R' U' R U' R' /U2 x' M' U' R U' R' U R U2 L' U R' U2 R /U R U R' U R U2 R' U' R2 D R' U R D' R' U' R'","R U R' U R U L' U R' U' L / R U R' U R U r' F R' F' r /U R' F R U R' U' R' F' R U' R U R' U R","U2 F R U' R' U R U2 R' U' R U R' U' F' / R' F R U R' U' R' F' R U R2 U2 R' U' R U' R' / x' M' U' R U' R' U R U2 L' U R' U2 R /U' R U R' U R U2 R' U' R2 D R' U R D' R' U' R'","U2 R U R' U R U L' U R' U' L /U2 R U R' U R U r' F R' F' r / L' U' L U' L' U' R U' L U R' / R' U' R U' R' U' L U' R U L'","U F R U R' U' R U R' U' R U R' U' F' /U' R U R' U y' R' U R U' R2 F R F' R / x' U' R U' R' U R' F2 R U' R U R' U x",],
"22": ["R U2 R2' U' R2 U' R2' U2' R","R' U' R U' R' U2 R U' L' U R U' L U R' / R' F2 R U2 R U2' R' F2 U' R U' R'","U F U R U' R' U R U2 R' U' R U R' F'","R U R' U R U2 R' U' R U' L' U R' U' L R U R' U' R' F R2 U R' U' R U R' U' F'","R U' L' U R' U L U L' U L","U x' R U' R' D R U2 R' D' R U2 R' D R U R' D' x / R U D' R U R' D R2 U' R' U' R2 U2 R / R2' D' R U R' D R U R U' R' U R U R' U R /U R U2 R' U' F' R U2 R' U' R U' R' F R U' R'",],
"23": ["R' U' R U' R' U2 R2 U R' U R U2 R'","U' r U R' U' r' F R2 x' U R' D' R U' R' x","x' R U' R' D R U2 R' D' R U' R' x / R' U' R U' R' U2 R2 U' L' U R' U' L","F R U' R' U R U R' U R U' R' F'","R2' D' R U2 R' D R U2 R","R' U2 R F U' R' U' R U F'",],
"24": ["U2 R' U2 R U R' U R2 U2 R' U' R U' R'","R' U R U2 L' R' U R U' L","U2 x' R U R' D R U' R' D' x","U2 F R U R' U' R U' R' U' R U R' F'","x R' U' R D' R' U R D x'","R' U R2 D r' U2 r D' R2 U' R",],
"25": ["U R U2 R' U' R U R' U' R U R' U' R U' R'","U2 R' U2 R' D' R U2 R' D R2","U x' R U R' D R U2 R' D' R U R' x","x D' R' U' R D R' U R x'","U x' D R U R' D' R U' R' x","U R' U' R U R' F' R U R' U' R' F R2",],
"26": ["R' U' R U' R' U2 R /U R U2 R' U' R U' R' /U2 L' U' L U' L' U2 L","U2 R2 D R' U R D' R' U R' U' R U' R'","U2 R L' U' L U R' U2 L' U2 L","U2 R U2 R' U2 L' U R U' R' L","R' U L U' R U L' /U2 L' U R U' L U R'","U2 R' U' R U' L U' R' U L' U2 R / L' U' L U' R U' L' U R' U2 L",],
"27": ["R U R' U R U2 R' /U L' U2 L U L' U L","L' U2 L U2 R U' L' U L R'","L' R U R' U' L U2 R U2 R'","U' R U R' U R U' R D R' U' R D' R2'","R U' L' U R' U' L /U2 L U' R' U L' U' R","L U L' U R' z R U R' D R2 U' z' / z U R U' R D' R U R' D R2 U'",],
"28": ["M U M' U2 M U M' / r U R' U' M U R U' R' / R B M' U M' U M' U2 M U M U M U2 B' R' / r U R' U' r' U2 R U R U' R2 U2 R","U x L2 U2 R' U' R U2 L' U r' /U r U R' F' R U R' U' R' F R2 U' r' /U' R2 B2 r' U' L U2 l' B' R' /U' R2 U R2 U F2 r U r' F2 R F' R'","U R' F R' F2 r U' r' F2 R2 / r U R' U' r' F R2 U' R' U' R U R' F' / M' U' R' U L' U2 R U' R' U2 R2 x'","r U' L U2 R' U R U2 L2 x'","R2' F2 r U L' U2 x l U' l","U R2 D' r U' r' D R2 U y R U R' / x' R2 F' R D' R' F R2 U' R' D R U x /U S R2 D' R U' R' D R2 y' U l U L' /U2 S R2 D R' U R D' R2 y U' l' U' L",],
"29": ["U' R' F R' F r U' R U' R U' r' F / F' L F' L2' U L U L' U' L F2' / r U2 R' U' R U' r' R' U2 R U R' U R /U' R U R' U R U' R' U r' U' R2 U' R2' U2 r","U' x R' U' R D' R' U2 R' U' R2 D x' /U' M' U' L' U l U2 r2' F r U' r / L' U' L U' L' U L F U F' U' L' U2 L","U' F R F' r U R2' U' M U R U' R' /U' M' U' M U' l' U' l F U F' l' U l","U' R U R' U' R U' R' F' U' F R U R' / F' U' L' U2 L U L' U2 L U F /U R U R' U R U2 R' U R U R' U' R' F R F'","U' r U R' U' M2' R' F R F' M' /U' M' U' M U' l' U' l F U F' l' U l /U' r U R' U' M L' U R U' R' L","R' F R F' R U2 R' U' F' U' F / R2' U' R F R' U R2' U' R' F' R /U2 r2' D' r U r' D r2 U' r' U' r",],
"30": ["F R' F R2 U' R' U' R U R' F2 /U L F' L F' l' U L' U L' U l F'","U' x' R U R' D R U2 R U R2' D' x /U M' U R U' r' U2 l2 F' l' U l' / R U R' U R U' R' F' U' F U R U2 R' /U R' U' R U' R' U2 R U' R U R' U' R' F R F'","U l' U' L U M R U' L' U L R' / R U R2 F' R U R U' R' F U' R' F R F'","F U R U2 R' U' R U2 R' U' F' /U L' U' L U L' U L F U F' L' U' L","U M' U M U r U r' F' U' F r U' r' / F' L' F l' U' L2 U M U' L' U L","r2 D r' U' r D' r2' U r U r' / L2 U L' F' L U' L2 U L F L' / L F' L' F L' U2 L U y R U R'",],
"31": ["L F2 l' U L U L' U l U2 F' L' / R U2 R' U' R U' R' U r U R' U R U2 r'","U' r U2 R' U' R2 U' r' F R' F'","U' R' U' F U R U' R' F' R /U S' L' U' L U L F' L' f /U S' r' F' r U r U' r' f","R' U' R' F R2 U' R' U2 R U R' F' R R U2 R' U' F' U F U R U2 R' /U2 R' U r' D' r U' r' D r U' R","U2 F R' F' R U R U R' U' R U' R' /U' R U R' U R U' R' U' R' F R2 U R' U' F'","U' R' U2' R U R' U' R B' R B R2' U2' R",],
"32": ["R' F2 r U' R' U' R U' r' U2' F R /U2 R' U2 R U R' U R U' r' U' R U' R' U2 r","U l' U2 L U L2 U l F' L F","R U2 R' F' L' U L F R U2 R'","U x' R U R' D R U' R U' R' U R' D' x /U2 F U R U R' U' y' R' U2 R U R'","U L U F' U' L' U L F L' /U' S R U R' U' R' F R f'","U L U2 L' U' L U L' B L' B' L2 U2 L' /U' R U2 R' U' R U R' F R' F' R2 U2 R'",],
"33": ["R U2 R' U' R U' R' r' U2 R U R' U r / R U' R' U R U' R' F l' U' R U R' U' l","U' r U r' R U R' U' R r U' r' F R' F'","U' F R U' R' U R U R' F' /U L' U' L U L F' L' F /U r' F' r U r U' r' F","U' R U R' F' U' R U R' U' R' F R2 U' R' /U2 R' U2 R U F R' U R2 U' R' F'","U' R U R' U' R' F R F'","U' R U' R' U' F' U2 F R' F R F' /U r U' r' U' r2 D r' U r D' r2",],
"34": ["U' R U R' U2' F2 U' r' F r2 U r' F","U2 R' U' R U' y R U' R' U' F R' F' R","U2 L U L' U' y' l' U' L U M / R U R2 U' R' F R U R U' F'","U2 F R F' r U r' U R' U' r U' r' / R U2 R2' F R F' R U' R' U' R' F R F'","U2 R' U' R U y r U R' U' M /U2 R' U' R U x U R D' R' U' D x' /U2 F R U R' U' R' F' r U R U' r'","U2 R2' D' R F R U R' U' F' U R' D R2",],
"35": ["U R' F R U r' F r y' R2 U' R' F R' F'","U' R U2 R' U' y' r' U r U' r' U' r","L' U2 L U y' r U' r' U r U r'","R2 D r' U r D' r' U' R' U M'","U R2 D' r U' r' D r U R U' M","U' R U2 R2' F R F' R U2 R'",],
"36": ["l' U2 L U L' U x' U' R U' R' U2 R /U R U R' F' R U R' U' R' F R U' R' F R F'","R' U' F2 u' R U2 R' D R U' R B","U' R U2 r D r' U2 r D' r' R' /U' R U R' U' F' U2 F U R U R'","F' L' U L S' U L' U' L f","U L' U' L U' L' U L U L F' L' F","U' R U R' U2 F' U' F U' R U' R'",],
"37": ["F R' F' R U R' F' R U R U' R' F R U' R' / l' U' L U' L' U2 x' U2' R U R' U R / F R U' R' F R U' R' U' R U R' F' R U R' F'","U' R U R' U' R' F R2 U' R' U R U R' F' /U' F R' F' R U R U' R'","U R U R' U R' U' R U' R' U2 F R F'","U' F R' F' R U R U' R'","U' F R U' R' U' R U R' F'","U2 R U2 R' F R' F' R2 U2 R' /U2 R2' F' R U R U' R' F R2 r' U' R' U r",],
"38": ["U2 L' U' L F L' U' L U L F' L' U L F' L' F /U' r U2 R' U' R U' x' U L' U L U2 L'","U2 R' U2 r' D' r U2 r' D r R / L' U' L U F U2 F' U' L' U' L","U2 R2 u' R U' R U R' u R F' U' F R","U2 R U R' U R U' R' U' R' F R F'","U' F R U' R' S U' R U R' f'","U2 L U L' U L U2 y' R U R' U' F' /U r' U' R U M' R' F' R U R' U' R' F R2 / R U R' U F' U F U2 R U' R'",],
"39": ["U' R U2 R' U' R U' x' U L' U L U2 l'","R' U' R f R f' R' U' R U R' U R","U' R' U' R U' R U R' U' R' U2 F R F'","R U' r' U' F' U F r R'","r U R U' r' F U R' U' F'","U2 F R U R' U' F' R' U' R U' R' U2 R",],
"40": ["L' U2 L U L' U x' U' R U' R' U2 r","U' F R U R' U' F' R U' L' U R' U' L","U R U R' F' U' F R U R' U' R U' R'","U F R U R' F' R' F U' F' U R","U R' F R U R' U' F' U R","U' F R U R' U' F' R U R' U R U2 R'",],
"41": ["U L F' L' F L F' L' F L' U' L U L' U' L","F U R2 D R' U' R D' R2' F'","F R' F' U2 R U R U' R' U R' U R","R' D' F r U r' F2 r U r' D R","M' L U L' U L U2 L2' U R U' L U r' / F' L' U' L F R U R' F' U L' U' L U F /U2 R' U R U' R' U R U R' U F' U2 F R /U R U2 R' U' F' U' F U R U' R' U R U2 R'","R U R' U R U2 R' F R U R' U' F'",],
"42": ["U' R' F R F' R' F R F' R U R' U' R U R' /U' R' F2 r U r' F R2 U2' R' U' R U' R'","U' R' U' F2 u' R U R' D R2 B","F R U R' y' R' U' R' F R2 U R' U' F' / M' R' U' R U' R' U2 R2 U' L' U R' U' l /U' F R U R' U' R' F' R2 U' R' F' U' F R U R' / R U R' U' R' F U' R2 U' R2 U2 R U' F'","U' F R' F' R U2 R' U' R2 U' R2' U2' R","F' L F U2 L' U' L' U L U' L U' L' /U' F R U' R' U' R U R' F' R U2 R' U' R U' R' / R U' R' U F' U' F U R U' R' U' R U R' / F R' U' R D' R U' R' D R' U2 R U' F'","U' r' U' r R' F R' F' R2 r' U r /U2 R' U' R U' R' U2 R F R U R' U' F'",],
"43": ["U2 x' R' D R U' R U' R D' R' U R' U x / r' U' R U' R' U2 r U' r' U2 R U R' U r /U2 r U R' U R U2 r' R' U' R U' R' U2 R","U2 x' R U R' D R U' x R2' F' R U R U' R'","U2 R r D r' U2 r D' r' U2 R' / R U R' F' U2' R U R' U' R' F R2 U' R'","U2 r' R U R' D R U' R U' R' U R' D' r","U r2 D' r U' r' D r R U' R' U2 r","U f' L' U' L U f",],
"44": ["x R D' R' U R' U R' D R U' R U' x'","U' f R2 D R' U R D' R2' U' f' /U x' R U' R' D R U l' U R U' R' F'","U r U R2' D' R U R' D R2 U2 r'","x' D R U' R U R' U R' D' R U' R' x /U2 R U2 R' U' F' U' F U R U2 R'","R' r' D' r U2 r' D r U2 R","U' f R U R' U' f' /U F U R U' R' F' /U L U F' L F L' U' L' /U' R U B' R B R' U' R'",],
"45": ["R' U' R U' R' U2 R r U R' U R U2 r' /U F2 L' U L U' L' U' L2 F L' F /U' F2 R U' R' U R U R2' F' R F' /U2 R U R' U R U2 R' r' U' R U' R' U2 r","U' F R2 D R' U R D' R2' U' F'","U' F R U' R D R' U2 R D' R2' U' F'","U' x' R U R' D R U' x U R' U' F' /U' R U R D R' U' R D' R2' F R U R' U' F' / R U R2 F R2 U R' U' F2 U2 F /U' F R' D' R U R' D R U' R U R' U' F'","U' F R2 D R' U' R D' R' U2 R' U' F'","U' F R U R' U' F'",],
"46": ["U R D r' U' r D' R2' U' R' F R F' R","U2 b' U' R2' D' R U R' D R2 b","U2 r U' r' U' r U r' U' y L' U2 L","U R U R' U F' L' U L F U' R U' R' /U R U R2' F' R U R U' R' U F R U' R'","U2 l' U l U l' U' l U y' R U2 R'","U R' U' R' F R F' U R",],
"47": ["U2 F' L' U' L U L' U' L U F","U F R' F' R U2 R U' R' U R U2 R'","U F' L' U L U L' U2 L U L' U' L U F / f' U f U2 R' U' R U' R2 U2 R","x R' U' R D' R' U R' U R2 D R' U' R x' /U2 F' U' F2 R U' R' U' R U R' F' R U' R'","U2 r U' r B r2' y' U2 R U' L' U L R'","U2 F R U' R' F' r' F' r U r' F r",],
"48": ["F R U R' U' R U R' U' F'","U F R' F' r U2 R U' R' U R U2 r'","U F R U' R' U' R U2 R' U' R U R' U' F' / F R' F' U2 R U R' U R2 U2 R'","R U2 R' U' R U R' U2 R' F R F'","F R U R' U' R2 D R' U R D' R2' U' F'","F' r' F r F R U R' U' R U' R'",],
"49": ["r U' r2 U r2 U r2 U' r","U' x R' U R D' R2 U' R U' R D R' U R x'","U' F' L' U L U L' U' L U' L' U L F","R' U' R2 U R' U' R' y r U r' U' R U' R'","U2 r' U r' F' r2 U2 F' r U r'","U R' U2 R U R' U R F R U R' U' F' /U2 R U R' U R U' R' F' U2' F R U' R'",],
"50": ["U2 l' U l2 U' l2' U' l2 U l'","U R' F R U R' D R2 U' R2' D' F' R","U' F R U' R' U' R U R' U R U' R' F'","U x' R U' R' D R2 U R' U R' D' R U' R' x","U2 R' U R U' R2' F R2 U R' U' F' R","U' R U2 R' U' R U' R' F R U R' U' F'",],
"51": ["f R U R' U' R U R' U' f'","U2 L' U2 L U2 L F' L2' U' L U F","R' U2 R U2 F R U R' U' F' R' U R","R U2 R' U2 R' F R2 U R' U' F'","F R U R D' R U' R' D R2 F' R' U R","U' R' U' R' F R F' R U' R' U2 R /U' R U2 R' U' F' U2' F U R U2 R'",],
"52": ["R' U2 R2 u R' U R U' R u' R' / R' U' x U R' U' R U R' U' R x' U R","U F U R U' R2' F' R U2 R U2 R'","U R U R' F' U' F U R' U' R2 U' R2 U2 R","U F' U' L' U L2 F L' U2 L' U2 L","U' R U' R' F' U' F U2' R U R' U' R U R'","U2 R U R' U R d' R U' R' F'",],
"53": ["U l' U2 L U L' U' L U L' U l /U' r' U2 R U R' U' R U R' U r","F R U R' U' F' R U R' U' R' F R F'","U R' F R F' U2 l2 F' l' U l'","F R U R' U' R U' R' U R U R' F'","b' U' R D U R' U' R D' R U R b","x U R' U R U2 l U' L' U R' U2 L",],
"54": ["U r U2 R' U' R U R' U' R U' r'","U2 F' L' U' L U L' U L U' L' U' L F","U L F' L' F U2 r2' F r U' r","U2 R U' L' U R' U L U2 L F' L' F","U F U' R U2 R2' F R F' R U' R' U2 F'","x' U' R U' R' U2 R' F r U' R U2 L'",],
"55": ["U R' F R U R U' R2' F' R2 U' R' U R U R' /U r U2 R' U' R2 r' U R' U' r U' r'","R U2' R2' U' R U' R' U2' F R F'","U R' F U R U' R2' F' R2 U R' U' R","U2 R U2' R2' U' R U' R' U2' F R F'","U' R' F U R U' R2' F' R2 U R' U' R","U F U' R2 D R' U2 R D' R2' U F'",],
"56": ["r' U' r U' R' U R U' R' U R r' U r","R' F R F' U2 R U' R' d R' U2 R / F R U R' U' F' r U R' U' r' F R F' /U2 F R U R' U' R F' r U R' U' r'","U2 F R U' R' F' U' F R U' l' U R' U' R U' x' /U2 F R U R' U2 y' R' U2 L R U' R' U L' / r U R' U R U r' U' r U r' y' R' U R","F R U R' U' R F' r U R' U' r' /U2 R' F R F' U2 R U' R' d R' U2 R /U2 F R U R' U' F' r U R' U' r' F R F'","F R U' R' F' U' F R U' l' U R' U' R U' x' / F R U R' U2 y' R' U2 L R U' R' U L'","L' U2 R U' L U l' U2 R' U' R U' x' /U r U2 R2 F R F' R U2 r' U' r U R' U R U2 r' /U F R U R' U' R U R' U' S R U R' U' f'",],
"57": ["R U R' U' M' U R U' r' / M U M U M U2 M' U M' U M' / M U' M U' M U2 M' U' M' U' M' / M' U' M' U' M' U2 M U' M U' M","U R2 B' R' B R' F' U' F R U R' /U2 R U' R' F' U F R x' U' R U R2 x /U2 R U' R' F' U F R U R2' F R F'","r U r' F' R U R' U' R' F R r U' r'","F R' F' R2 U' R' F' U' F R U R' / R U' R' F' U F R x' U' R U R2 x","l' U' l F L' U' L U L F' L' l' U l","R U' R2' F R F' R d' R U2 R' F'",],
}

var COLL = {
	"Sune":["R U R' U R U2' R' ","R U' L' U R' U' L ","U2' R' U' R U' R2' D' R U2 R' D R2 ","U' R U R' U R U' R D R' U' R D' R2' /U2' R2' D' R U' R' D R U' R U R' U R","R2' F R U R U' R' F' R U' R' U R /U2 R2' D' R U2 R' D R2 U R' U R /U R' D' R U R' D R2 U R' U2' R U R'","U2' R U R' F' R U R' U R U2' R' F R U' R' ",],
	"AntiSune":["R' U' R U' R' U2 R ","U2' L' U R U' L U R' ","U2' R' U' R U' R2' D' R U2 R' D R2 ","R U R' F' R U2 R' U' R U' R' F R U' R' ","R U R' F' R U2 R' U2' R' F R2 U' R' /U2 R2 D R' U2' R D' R2' U' R U' R'","U R' U' R U' R' U R' D' R U R' D R2 ",],
	"L":["R U R' U R U' R' U R U' R' U R U2' R' ","U' R U2' R D R' U2 R D' R2' /U2 R' F' R U R' U' R' F R2 U' R' U2 R","U' F R' F' r U R U' r' ","R' U' R U R' F' R U R' U' R' F R2 ","U2 R' U2' R' D' R U2 R' D R2 ","F' r U R' U' r' F R ",],
	"T":["R U2' R' U' R U' R2' U2' R U R' U R ","R' U R U2' L' R' U R U' L /R' U' R' U' R U R' F' R U R' U' R' F R'","U (l' U' L U) (R U' r' F) ","U2 F R U R' U' R U' R' U' R U R' F'","R U R' U' R2 D R' U2 R D' R2' U R U' R'","U' (r U R' U') (r' F R F')",],
	"U":["U2' R U R' U R U2' R2' U' R U' R' U2 R ","U2' R 2 D R' U2 R D' R' U2 R' ","R' F R U' R' U' R U R' F' R U R' U' R' F R F' R /U' r U R' U' r' F R2 U' R' U' R U2 R' U' F'","F R U' R' U R U R' U R U' R' F'/R' U2' R U R' U R' D' R U' R' D R U R","R2' D' R U2 R' D R U2 R ","R2' D' R U R' D R U R U' R' U' R ",],
	"Pi":["R U2' R2' U' R2 U' R2' U2' R ","U' R' U' R U' R' U R U' R' U R' D' R U R' D R2 /R' F2 R U2' R U2' R' F2 U' R U' R'","U' R U R' U F' R U2 R' U2' R' F R /U2' L' U R U' L U' R' U' R U' R'","U R U2 R' U' F' R U2 R' U' R U' R' F R U' R'/r' U' R U' R' U R U' R' U R' F R F' U r/U2 R U2' R' U R' D' R U R' D R2 U' R' U R U' R'","U R U R' U R U' R' U R U' R D R' U' R D' R2'/R U2 R' U' R U R' U2' L' U R U' L R'/U' R U R' U F2 R U2' R' U2' R' F2 R","R' U' F' R U R' U' R' F R2 U2' R' U2 R/U F U R U' R' U R U2' R' U' R U R' F'",],
	"H":["R' U' R U' R' U R U' R' U2 R /R U R' U R U' R' U R U2' R' /U R U2 R' U' R U R' U' R U' R' ","F R U' R' U R U2 R' U' R U R' U' F'","F R U R' U' R U R' U' R U R' U' F'","R' F' R U2 R U2' R' F U' R U' R'/U' l U' R U R' l' U L F' L' U L F L'/R U R' U R U L' U R' U' L",],
}
var test = {
	"test1":["RUR'U'", "U R U2 R' U' F' R U2 R' U' R U' R' F R U' R'/ r' U' R U' R' U R U' R' U R' F R F' U r/ U2 R U2' R' U R' D' R U R' D R2 U' R' U R U' R'","U R U R' U R U' R' U R U' R D R' U' R D' R2'/ R U2 R' U' R U R' U2' L' U R U' L R'/ U' R U R' U F2 R U2' R' U2' R' F2 R"]
}


var olfc = {
	"all":["U R U2 D R' U R D R", "U' R' U' R D2 R", "D2 R' U' R U' D2 R' D2 R", "U R U' R U' D2 R'", "R2 U2 R U' R U R2D2 U R", "U' R' U2 R D2 R", "R U R' U' R U' D2 R", "R D R' U RU2' D R", "D R U' D R", "D R U RU2' D R", "U R U2' D2 R", "R U R2 U' R U' D2 R", "U' R U2 R'D2 R", "R U R' U' R2U' D2 R", "U' D' R U' R'D' R", "R D' R D R U' D2 R", "D R' D' R'  D2 U' R", "D R' D' R'  D2 U' R", "U' R U' R'D2 R", "R U D R U' RU' D R", "R D' R' U RD' U2' R", "U2 R U2 R2U' D2 R", "R D R U R'U2' D R"]
}

var CR = {
		"UF<->UB" :[ "R B' R D2 L' F L D2 R2 B", "R' U' R U' R2 D' L F2 L' D R2", "(U') R2 D' L F2 L' D R2 U R' U R", "y L U2 L U' L U L U' L2 U' L' ", "(U) B' R2 U' R2 U R2 B U' F' U' F", "(U') y L' U' L U' L' U L U2 L' U' L", "(U) R U' R' U R U2 R' U' R U R' ", "(U') R' U2 R' U' R' U R' U' R2 U' R", "y L U L2 U L' U' L' U L' U2 L' ", "(U) R U' R' U R U R' U R U' R'", "(U') R' U R2 U R U' R U R U2 R", "y L U2 L U2 L2 D L' U2 L U2 D' L" ],
		"UF<->UL" :[ "R' U' R B U B' R B' R' B2 U' B' ", "(U2) R U' R' U L' B2 D' R' D B2 L", "L' B2 D' R D B2 L U' R U R' ", "(U2) y L2 U' L2 U' L2 U2 L2", "(U) y L' U' L U2 L' U' L", "F' U2 F B U B2 D' R2 D B  ", "(U') y L2 U2 L2 U L2 U L2", "(U) R' U' R2 U' R2 U2 R2 U' R'", "(U) R U' R' U' R U2 R' ", "B' R2 U' R2 U2 R2 U' R2 U' B", "(U2) R U2 R' U R U R' ", "(U) R U R2 U2 R2 U R2 U R " ],
		"UL<->UB" :[ "(U) R U2 R' U2 B' U' R U R' B", "R U2 R D L' B2 L D' R2", "(U') R2 D L' B2 L D' R' U2 R'  ", "R2 D' L F2 L' D R U2 R", "(U) y L2 U' L U' L' U2 L U' L", "(U') R2 B U' B' U' B U2 B' U' R2", " F2 L2 D' B2 D' B2 D2 L2 F2", "(U') R2 U R' U R U2 R' U R' ", "R U2 F U R' U' R F' U2 R' ", "(U) F2 L2 D2 B2 D B2 D L2 F2", "R U2 R L' D B2 D' L R2", "(U') R U' R U2 R' U' R U' R2" ],
		"Clockwise" :[ "y M2 U' M' U2 M U' M2", "(U) y R U2 R2 U2 R2 U R2 U R2 U' R' ", "R' U2 R U R' U R", "L2 D R' F2 R D' L' U2 L' ", "(U) F2 U2 F2 R' U F2 U F2 U' R", "F2 L U' F2 U' F2 U L' U F2", "F2 L2 U' F2 U' F2 U L2 U F2 ", "B R U2 B' U' B U' R' B'", "(U2) L' R2 U R2 U' L U2 R2 U2 R2", "(U) y L2 U2 L2 U L2 U L2 ", "(U2) F' L2 B' U' B U L2 F", "(U) F' R U2 R' U' R U' R' F" ],
		"AntiClockwise" :[ "y M2 U M' U2 M U M2", "L' U' L U' L' U2 L ", "(U') L U L2 U' L2 U' L2 U2 L2 U2 L' ", "(U') F2 L2 D2 B2 D B2 D L2 F2", "(U) R U R' F' U' L' U2 L U F ", "(U) R U' L' U' L U' L' U2 L R'", "F' U' R' U' F U F' R U F", "(U') B' R B2 L U L' U' B2 R' B", "L U2 L D R' F2 R D' L2", "(U') y L2 U' L2 U' L2 U2 L2", "(U) F' L' U2 L U L' U L F", "R2 B U B' U' R2 F' U2 F" ],
}
window.algs = {
	"ZBLL" :zbll_full,
	"EG-1": eg_full,
	"OLLCP": ollcp ,
	"COLL": COLL,
	"algdbOLLCP": algdbOLLCP,
	"OL5C": olfc,
	"CR" : CR
};
