var eg_full = {
  "Sune": ["(U') F' L U2 F2 R U' x'", "R U R' F2 U F R U R' ", "(U') R' F R U2 R U' R2 F2 R F'",
           "F' U R U' R' U F R U R'", "(U) R U' R' U R U' R' U F R U' R'", "R' F R2 U' R' U L F' L' F"],
  "AntiSune": ["(U') B U' R2 F2 U' F" , "(U) R U' R' F' U' F2 R U' R'","F' R U R' U' R U R2' F' R",
               "R U' R' F' U' R U R' U' F", " (U') R U R' F' U' R U R' U' R U R'", "(U2) R U' R2 F R U' R' F R F'"],
  "Pi": ["(U2) R2 B2 R' U R' U' R U2 R U' R2", "(U') R' F R2 U' R2 F R", "(U') F R' F U' F2 R U R",
         " (U') R U' R' U R U' R' F R U' R'", "(U) F U' R U2 R' F' R U R' F'", "F R U' R' F R U2 R' U F'"],
  "U" : ["R U' R2' F R2 U R' U' R U' R'", "(U2) x U' R' U R U' F R U R U'", "(U) F' U2 R U2 R' U2 F",
         "(U2) R' F R F' R' F R2 U' R'", "(U2) R' F R F' U R U' R' F R U' R'", "(U') R' F R2 U' R' U y' R U R'"],
  "L" : ["R U' R' U R U' R2 F' R F", "(U2) (F R' F' R) U2 R U' R2 F' R2 U R'", "R' U R2 U' R2 U' F R2 U' R'",
         "R' F R2 U R' F' R U2 R'", "(U) L' U L y' R U2 R U' R2", "(U) R' U2' F R U2 R U' R2 F"],
  "T" : ["(U2) R2 U R U' R2 F R U2 R' F", "(U2) R2 U R U' R2 F R U2 R' F", "(U2) R U' R2 F R U R U2 R'",
         "R2 B2 U' R' U' R U' R' U R'", "(U2) R U R2 x U' R U R' U' R", "(U') R U' R' U2 F R U2 R' F"],
  "H" : ["R' F R2 U' R2 U' F U R", "F' U R U' R2 F2 R U' F", " R' U' R' F2 U F' R F'", "R U R' F' R U R' U' R U R' U'"]
}

var zbll_full = {
    
    "T1": ["(U') R U R' U R U2 R' U2 R' U' R U' R' U2 R", "R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'", "(U2) R' U2 R U R' U R2 U2 R' U' R U' R'", "R U2 R' U' R U' R2 U2 R U R' U R", "R' U R U2 R' U' R U2 R' U' R U' R' U R", "(U2) R U' R' U2 R U R' U2 R U R' U R U' R'", "R' U R2 U R' U R' U' R U' R' U' R U R U' R'", "(U') R U R' U R U' R' U R' U' R2 U' R2 U2 R", "(U2) R' U2 R U R' U R U' R' U' R U' R' U2 R", "R U2 R' U' R U' R' U R U R'U R U2 R'", "(U') R' U' R2 U R2 U R2 U2 R' U R' U R ", "(U') R U R2 U' R2 U' R2 U2 R U' R U' R'"],
    "T2": ["(U) R U R' U R U R2 D' r U2 r' D R2 U R'", "(U) R' U' R U' R' U' R2 D r' U2 r D' R2 U' R", "(U2) R U' R2 D' r U2 r' D R2 U R'", "R' U R2 D r' U2 r D' R2 U' R", "R' U' R U2 R D R' U' R D' R2 U R U' R' U R", "(U') R U2 R' U' R U r' F r U2 R' r' F r", "R' U' R U R2 D' R U2 R' D R2 U2 R' U2 R", "(U) R U R' U' R U R2 D' R U' R' D R U2 R U' R'", "(U) R' D' R U' R' D R U' R U' R' U R U' R' U' R U R'", "R U' R' U R U R' U' R U R' U R' D' R U R' D R", "(U) R U R D R' U R D' R' U L' U R' U' L ", "(U2) R2 F R U R' U' R' F' R' U' R2 U2 R U2 R"],
    "T3": ["R' U R U2 L' R' U R U' L ", "R' U2 R U R2 F R U R U' R' F' R", "(U2) R' U' R2 U R' F' R U R' U' R' F R2 U' R' U' R' U R", "(U2) r U' r U2 R' F R U2 r2 F", "(U') R' U' R' D' R U R' D R U2 R U R' U R", "R' U' R y R U R' U' R l U' R' U l'", "(U) L' U2 R U2 R' U2 L U R U R' U' R U' R'", "F U' R' U2 R U F' R' U' R U R' U R", "(U2) R' U' R U' R' U R F U' R' U2 R U F'", "R U R' U R U' R' U' L' U2 R U2 R' U2 L", "R' U2 R U R' U R F U R U2 R' U R U R' F'", "r' U' l' U2 R U' R' U2 l R U' R' U2 r"],
    "T4": ["(U') l' U2 R' D2 R U2 R' D2 R2 x'", "R' U2 R U' R' F R U R' U' R' F' R U' R", "R' U2 R' D' R U2 R' D R' U R' U R U2 R'", "(U2) R U2 R D R' U2 R D' R U' R U' R' U2 R", "R' D' R U R' D R U2 R U2 R' U R U R'", "(U) R' U' R' D' R U R' D R U' R U' R' U2 R", "R' U R2 D R' U R D' R' U R' U' R U' R' U' R ", "(U2) R U' R2 D' R U' R' D R U' R U R' U R U R'", "(U) R' U' R U' F U' R' U R U F' R' U R", "R' D' R U R' D R2 U R' U2 R U' R' U' R U' R'", "(U2) F R U R' U' R U' R' U' R U R' F'", "(U') R U R' U2 R U' R' U2 R U' R2 F' R U R U' R' F"],
    "T5": ["R U R D R' U' R D' R2", "(U') R U2 R' U2 R' F R U R U' R' F'", "(U2) R2 B2 R' U2 R' U2 R B2 R' U R U' R'", "(U') R' D' R U R' D R2 U' R' U R U R' U' R U R'", "(U') F' U' r' F2 r U' r' F' r F ", "(U') R U R' U' R U' R' L U' R U R' L'", "(U) R U R' U R U R' U2 L R U' R' U L'", "R' U' R U' R2' F' R U R U' R' F U R U' R' U2 R", "(U) R' U' R U R' U' R2 D R' U2 R D' R' U R' U R", "(U2) R U R D R' U2 R D' R' U' R' U R U' R' U' R U' R'", "(U2) F R U R' U' R' F' U2 R U R U' R2 U2 R", "(U') R U' R' U' R U R D R' U2 R D' R' U' R'"],
    "T6": ["x' U' R' D R U R' D' R x", "(U) R U R' U' R' F' R U2 R U2 R' F", "R2 F2 R U2 R U2 R' F2 R U' R' U R", "(U') R D R' U' R D' R2 U R U' R' U' R U R' U' R", "(U) F U R U2 R' U R U R' F'", "R U R' U' R U' R'  U' F R U R' U' R' F' R", "(U) R' U' R U' R' U' R U2 L' R' U R U' L", "(U) F R U R' U' R U R' U' F' R U R' U' R' F R F'", "(U) R U R' U' R U R2 D' R U2 R' D R U' R U' R'", "R' U2 R F U' R' U R U F' R' U R", "(U) R' U2 R2 U R' U' R' U2 F' R U2 R U2 R' F", "(U') R' U R U R' U' R' D' R U2 R' D R U R"],

    "U1": ["(U) R U2 R' U' R U' R' U2 R' U2 R U R' U R", "R U R' U' R U' R U2 R2 U' R U R' U' R2 U' R2", "R' U' R U' R' U2 R2 U R' U R U2 R'", "(U2) R U R' U R U2 R2 U' R U' R' U2 R", "(U') R U R' U' R U' R' U2 R U' R' U2 R U R'", "(U') R' U' R U R' U R U2 R' U R U2 R' U' R", "(U) R U2 R2 U' R2 U' R' U R' U' R U R' U R", "(U) R' U2 R2 U R2 U R U' R U R' U' R U' R'", "(U) R' U2 R U R' U R U R' U' R U' R' U2 R", "(U) R U2 R' U' R U' R' U' R U R' U R U2 R'", "R' U' R U' R U2 R2 U' R2 U' R2 U R", "(U2) R U R' U R' U2 R2 U R2 U R2 U' R'"],
    "U2": ["(U2) R' U' R U' F U' R' U R U R' U R U' F'", "R U R' U L' U R U' M' x' U' R U' R'", "(U') R U2 R2 F R F' M' U' R U' R' U M", "(U') R' U2 R F U' R' U R U R' U R U' F'", "(U2)  R2 D R' U' R D' R' U' R' U R U R'", "R2 D' R U R' D R U R U' R' U' R", "R U' R' U' R U R D R' U R D' R2", "(U2) R' U R U R' U' R' D' R U' R' D R2", "M U' M' F R U R' U' F' M U M'", "(U') F R U R' U' R U R' U' F' U' R' F' U' F U R", "F R U' R' U' R U2 R' U' R U' R' U' R U2 R' U' F'", "(U) r' U' R' F R U r F R U' R' F'"],
    "U3": ["R' F R U' R' U' R U R' F' R U R' U' R' F R F' R", "(U') F2 R U' R' U' R U R' F' R U R' U' R' F R F2", "R U' R' U R U' L U r' F U2 R U2 R2 x", "(U) R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R' U2 R", "(U) R U' L U L' U R' U' l U2 R U2 R2 x", "(U) R' U L' U' L U' R U l' U2 R' U2 R2 x'", "F R U R U2 R' U' R U' R' U2 R' U2 R U' R' U' F'", "(U') r U R' U' r' F R2 U' R' U' R U2 R' U' F'", "(U) F U R U2 R' U R U R2 F' r U R U' r'", "(U') R U2 R' U2 R' F R U R U2 R' U' R U2 R' U' F'", "(U') R' U' R F R2 D' R U R' D R2 U' F'", "(U') r U R' U' r' F R U R' U' R F' R' U R"],
    "U4": ["x R2 U2 R' D2 R U2 R' D2 R' x'", "(U2) x R2 D2 R U2 R' D2 R U2 l", "R U R' U R U' R' U2 R' D' R U2 R' D R2 U' R'", "(U') R' U2 R U R' U R' D R' U2 R D' R' U2 R'", "(U') R U' R' U' R U' R' U R' D' R U R' D R2 U R'", "(U') R' U R U R' U R U' R D R' U' R D' R2 U' R", "R' U2 R U R' U R' D' R U' R' D R U R", "R U' R' U' R U2 R' U2 R' D' R U' R' D R", "R' U' R U2 R' F' R U R' U' R' F R2 U2 R' U R", "(U2) R U R' U R U R' U2 R U' R2 D' R U' R' D R", "F R U' R' U R U R' U R U' R' F'", "(U) F' R U R' U' R' F R2 U R' U2 R U R' U2 R U' R'"],
    "U5": ["R2 D' r U2 r' D R U2 R", "R2 D' R U2 R' D R U2 R", "R U' R' D R' U' R D' R2 U R' U' R' U2 R'", "(U2) R U R' U R U2 R2 U z U R' D R U' z'", "(U) R2 D' R U' R' D R2 U' R' U2 R", "(U') R' U R U R' U2 R U2 y R U' R' U2 R U' R'", "(U') R2 D R' U R D' R2 U' R U' R' U2 R U' R' U2 R U R'", "(U) R U L' U R' U' L U' R U R' U R U' R'", "(U') R' U2 R2 D R' U2 R D' R2 U R U2 R' U2 R", "(U') R U R' U2 F2 R U2 R' U2 R' F2 R2 U R'", "(U') R' U2 R' D' R U2 R' D R U2 R U R' U R", "(U') R' U R U' R' U' R U2 R D R' U' R D' R2 U' R"],
    "U6": ["R' U2 R U R2 F' R U R U' R' F R", "(U2) R2 D R' U2 R D' R' U2 R'", "R' U' R U R U R' U' R' U F R U R U' R' F'", "R U' R' U' R U2 R' U' R' D' R U2 R' D R", "(U) R U R2 D' R U R' D R2 U2 R'", "(U') R U' R' U' R U2 R' U2 y' R' U R U2 R' U R", "(U) R' U R' U' D' R U' R' U2 R U' R' D R U' R", "(U) R' U' L U' R U L' U R' U' R U' R' U R", "(U') R' U' R U R' U R U2 F R' U R U' F' R' U2 R", "(U) R U R' U R U' R' U R U' R' U' L' U R U' R' L", "(U') R U2 R D R' U2 R D' R' U2 R' U' R U' R'", "(U') R U' R' U R U R' U2 R' D' R U R' D R2 U R'"],

    "L1": ["R U2 R' U2 R' U' R U R U' R' U2 R' U2 R", "R U R' U R U' R' U R U' R' U R U2 R'", "(U2) R U2 R' U' R U' R' U2 R U R' U R U2 R'", "(U2) R U R' U R U2 R' U2 R U2 R' U' R U' R'", "R2 U R' U R' U' R U' R' U' R U R U' R2", "(U') R2 U' R U' R U R' U R U R' U' R' U R2", "(U) R' U2 R U R' U R U' R U2 R' U' R U' R'", "(U2) R U2 R' U' R U' R' U R' U2 R U R' U R", "(U) R2 U R' U' R' U R U R' U R U' R U' R2", "(U2) R2 U' R U R U' R' U' R U' R' U R' U R2", "(U2) R U R' U R U2 R' U R' U' R U' R' U2 R", "(U) R' U' R U' R' U2 R U' R U R' U R U2 R'"],
    "L2": ["F R U' R' U' R U R D R' U' R D' R' U2 R' U' F'", "(U) F R U R' U' R U' R' U2 R U2 R' U' F'", "L' U2 R U' R' U2 L R U' R'", "R' U' R U R' F' R U R' U' R' F R2", "F R U R' U' R' F R2 U' R' U' R U R' F2", "R' U' R U R' U' R' F R2 U' R' U' R U R' F' U R", "(U) r U2 R r2 F R' F' r2 U2 r'", "(U2) r U2 r2 F R F' r2 R' U2 r'", "(U2) F R U R' U' F' r U r' U R U' R' r U' r'", "(U) r U r' R U R' U' r U' r' F U R U' R' F'", "(U) R U2 R' U' L' U2 R U R' L U L' U L", "(U) R U R' U' R' U2 R' U D R' U' R U2 D' R"],
    "L3": ["(U') F' r U R' U' r' F R", "R' U' R U R' F2 R U2 R' U2 R' F2 R2", "(U') F' R U2 R' U2 R' F R U R U' R'", "(U) R' U R U' R' U R U R' U' R2 D R' U R D' R'", "F R U' R' U' R U2 R' U' F'", "(U2) R' U' R U2 R' F' R U R' U' R' F R2 U R' U2 R", "R' F R U R U' R' F' U R U R' U R U' R'", "R' U R U2 R' L' U R U L U r' F r", "(U) F R' F' R U R U' R' F U R U' R' U R U' R' F'", "(U') F' R U2 R' U2 R' F U2 R U R U' R2 U2 R", "(U2) R U R' U R' D' R U2 R' D R2 U' R' U R U' R'", "(U) R' U' R' D' R U2 R' D R U R U' R' U' R"],
    "L4": ["(U2) F R' F' r U R U' r'", "(U') R U R' U' R B2 R' U2 R U2 R B2 R2", "(U2) F R U R' U' R' F' R U2 R U2 R'", "(U2) R U' R' U R U' R' U' R U R2 D' R U' R' D R", "(U) F' r' F r U r' F2 r U F", "(U) R U R' U R U R' U' R U R D R' U2 R D' R' U' R'", "(U) L R U' R' U R L' U R' U R U' R'", "(U) L U' R U R' L' U2 R U' R' U' R U' R'", "(U) R' U2 R U R' U' F' R U R' U' R' F R2 U R' U R", "(U) R' U2 R2 U R' U' R' U2 F R U R U' R' F'", "(U) R U R' U R U' R' U' L' U R U' M' x'", "(U2) R U R D R' U2 R D' R' U' R' U R U R'"],
    "L5": ["(U) R' U2 R' D' R U2 R' D R2", "(U) R' U2 R' D' r U2 r' D R2", "(U2) R D R' U2 R D' R' U' R' U2 R U' R' U' R", "(U2) R U2 R U R U' R2 D R' U R D' R U R'", "(U) R U R' U2 R U R' U2 y' R' U2 R U' R' U' R", "R' U2 R U R2 D' R U R' D R2", "(U) R U R' U' R U' R' U L' U R U' L U' R'", "(U) R U' R' U2 R U R' U2 R U R' U R2 D R' U' R D' R2", "(U) R' U2 R U2 R' U' R2 D R' U2 R D' R2 U2 R", "(U2) F' R U R' U' R' F R2 U' R' U' R U' R' U R U R'", "R U' R2 F2 R U2 R U2 R' F2 U2 R U' R'", "(U) R' U R2 D R' U R D' R' U2 R' U R U R' U' R"],
    "L6": ["(U2) R U2 R D R' U2 R D' R2", "(U) R' F' R U R' U' R' F R2 U' R' U2 R", "(U') L' U R U' L U R2 U2 R U R' U R", "(U') F R U R' U' R' F' U' R U R U' R' U' R' U R", "(U2) R' U' R U2 R' U' R y U2 R U2 R' U R U R'", "(U') R U2 R' U' R2 D R' U' R D' R2", "(U2) R' U' R U R' U R U' L U' R' U L' U R", "(U2) R' U R' D' R U R' U2 R U R' D U R U' R", "(U2) R U2 R' U2 R U R2 D' R U2 R' D R2 U2 R'", "(U') R U R' U R U2 R D R' U2 R D' R' U2 R'", "(U') R' U R2 B2 R' U2 R' U2 R B2 U2 R' U R", "(U2) R U' R2 D' R U' R' D R U2 R U' R' U' R U R'"],

    "Pi1": ["R' U' R U R U2 R' U' R U' R2 U2 R", "R U R' U' R' U2 R U R' U R2 U2 R'", "(U') R' U2 R U R' U R2 U R' U R U2 R'", "(U) R U2 R' U' R U' R2 U' R U' R' U2 R", "(U') R U2 R' U2 R U' R' U2 R U' R' U2 R U R'", "(U) R' U2 R U2 R' U R U2 R' U R U2 R' U' R", "(U2) R U' R' U2 R U R' U2 R U R' U2 R U2 R'", "(U2) R' U R U2 R' U' R U2 R' U' R U2 R' U2 R", "R' U2 R2 U R2 U R2 U2 R'", "R U2 R2 U' R2 U' R2 U2 R", "R U R' U' R' U' R U R U R' U' R' U R U' R U' R'", "R U2 R' U' R U' R' U' R U2 R' U' R U' R'"],
    "Pi2": ["F R2 U' R U' R U' R' U2 R' U R2 F'", "(U2) F R2 U' R U2 R U R' U R' U R2 F'", "F U R' U' R2 U' R2 U2 R U2 R U R' F'", "r' U' R U' R' U R U' R' U R' F R F' U r", "(U) R U2 R' U' F' R U2 R' U' R U' R' F R U' R'", "(U) R' U' R' D' R U R' D R U2 R' D' R U2 R' D R2", "(U') R' U' R U R' U' R2 D R' U R D' R' U R' U2 R", "(U) R U R' U' R U R2 D' R U' R' D R U' R U2 R'", "(U2) R U2 R' U R' D' R U R' D R2 U' R' U R U' R'", "(U2) R' U2 R U' R D R' U' R D' R2 U R U' R' U R", "R2 D R' U' R D' R' U' R' U R U' R' U' R U' R'", "R2 D' R U R' D R U R U' R' U R U R' U R"],
    "Pi3": ["(U') F U R U2 R' U R U R' F' R U2 R' U' R U' R'", "r U' r' U' r U r' U' l R U' R' U l'", "r' U r U r' U' r U R2 F R F' R", "r' U' R U' R' U2 r U' R U2 R' U2 R' F R F'", "R' U' R U R2 F' R U R U' R' F U' R U R' U R.", "R U2 R D' R U' R' D R' U' R2 U2 R", "R' U' R U' R2 D' R U R' D R2 U' R' U2 R", "(U2) L' U R U' L U' R' U' R U' R'", "R U' L' U R' U L U L' U L", "(U) R2 D' R U2 R' D R2 U R2 D' R U R' D R2", "(U') R2 D R' U2 R D' R2 U' R2 D R' U' R D' R2", "(U2) R U2 R' U' R U r' F2 r U2 R' U' r' F r"],
    "Pi4": ["(U) R U2 R2 U' R U' R' U2 F R U R U' R' F'", "(U') R U R' U R U2 R2 F' r U R U' r' F", "(U') r' F' r U' r' F2 r2 U R' U' r' F R F'", "F R U R' U' R' F' R U2 R' U' R2 U' R2 U2 R", "(U) R' U' R L U2 R' U2 R U2 L' U R' U2 R", "(U') F U' R U' R' U R U R' U2 R U2 R' U F' U", "(U) R2 D' R U' R' D R U R' D' R U R' D R U R U' R' U' R", "R' U' F' R U R' U' R' F R2 U2' R' U2 R", "(U') R U R' U R U' R' U' R' F' R U2 R U2' R' F", "(U2) R' U' R' D' R U R' D R' U R' U R U2 R'", "(U2) R U R D R' U' R D' R U' R U' R' U2 R", "(U) F U R U' R' U R U2 R' U' R U R' F'"],
    "Pi5": ["r' F' r U r U2 r' F2 U' R U R' U' R U' R'", "(U2) R U2 R' U2 R' F R2 U' R' U2 R U2 R' U' F'", "R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R", "R' L U2 R2 U R2 U R U L' U' R U2 R'", "l U2 l' U2 R' U2 R B2 U R' U R", "(U') R U R' U F2 R U2 R' U2 R' F2 R", "(U') R' U2 R U R' U R2 U' L' U R' U' L", "(U) R U R' U R U' R' U R U' R D R' U' R D' R2", "R U R' U' R' F R2 U R' U' R U R' U' F'", "(U2) R' U' R U' R' U' R U' x' U L' U L U2 R U' R' U x", "R U2 R' U' R U R' U2 L' U R U' M' x'", "(U') L R' U' R U L' U2 R' U R U' R' U2 R"],
    "Pi6": ["(U') R U R' U R U' R' U F2 r U2 r' U' r' F r", "(U) F U R U2 R' U2 R U R2 F' R U2 R U2 R'", "R U' R' U' R U' R' U R U R' U R' F' R U R U' R' F", "R L' U2 R2 U' R2 U' R' U' L U R' U2 R", "R' F2 R U2 R U2 R' F2 U' R U' R'", "(U) R' U' R U' B2 R' U2 R U2 l U2 l'", "(U) R U2 R' U' R U' R2 U L U' R U L'", "(U') R' U' R U' R' U R U' R' U R' D' R U R' D R2", "(U) F U R U' R' U R U' R2 F' R U R U' R'", "R U R' U R U2 R' U' R L' U R' U' L U2 R U2 R'", "R' U2 R U R' U' R U2 L U' R' U R L'", "(U) R L' U R' U' L U2 R U' R' U R U2 R'"],

    "H1": ["R U2 R' U' R U' R' U' R' U' R U' R' U2 R", "R' U2 R U R' U R U R U R' U R U2 R'", "(U) R' U' R U' R' U R U' R' U2 R", "(U') R U R' U R U' R' U R U2 R'", "R' U2 R U R' U' R U R' U R", "R U2 R' U' R U R' U' R U' R'", "(U) R U R' U R U' R' U R U' R' U R' U' R2 U' R' U R' U R", "(U) R U R' U R U2 R' U' R' U2 R U R' U R"],
    "H2": ["(U) x' U' R U' R' U R' F2 R U' R U R' U x", "F U R U' R' U R U' R' U R U' R' F'", "R U R' y' U R' U R U' R2 F R F' R", "R' U' R y U' R U' R' U R l U' R' U l'", "F R U R' U' R U R' U' F' U R' F' U' F U R", "R' U' R U' R' U2 R U R' U' R U R' F' R U R' U' R' F R2", "(U) L' U L U' L' U' L U R' U' R U L' U' L U2 R' U' R", "(U) R U' R' U R U R' U' L U L' U' R U R' U2 L U L'"],
    "H3": ["(U2) R U R' U R U2 R' F R U' R' U' R U2 R' U' F'", "l U' R U R' l' U r U' r' U r U r'", "(U2) R' F R' F' R2 U' r' U r U' r' U' r", "(U) R' U' R U' R' U' L U' R U L'", "(U) R U R' U R U L' U R' U' L", "(U') R' U' R U' R U R2 U R2 U L' U R' U' L", "(U') R U R' U R' U' R2 U' R2 U' L U' R U L'", "R U2 R2 U' R' D R' U' R D' R U2 R", "R U2 R' U' R2 D R' U R D' R2' U' R U' R'", "(U2) R U R' U' L' U2 R U2 R' U L U' r' F2 r", "(U') R2 D' R U' R' D R2 U' R2 D' R U2 R' D R2", "(U') R2 D R' U R D' R2' U R2 D R' U2 R D' R2'"],
    "H4": ["(U2) F R' F' r U R U' r2 F2 r U r' F r", "(U) R U R' U' R' F R U R U' R' F' R U R' U R U2 R'", "R' U2 R U' L U2 R' U2 R U2 L' R' U R", "R U2 R' U L' U2 R U2 R' U2 L R U' R'", "(U') F U' R U2 R' U2 R U' R' U' R U R' U F'", "(U') R' F R U R' U' F' R U' R' U R' F R F' U R", "(U') R U2 R' U' R U' R D' R U' R' D R U R", "R U2 R2 F U' R2 U' R2 U F' U R", "(U2) R' U2 R U2' R2 F' R U R U' R' F U R", "(U') F B' R2 B R2 U' R2 U' R2 U R2 F'", "(U2) F R U R' U' R' F' U2 R U R' U R2 U2 R'", "(U) F R U' R' U R U2 R' U' R U R' U' F'"],

    "S1": ["(U') R' U R2 U R' U R U2 R U2 R U R' U R2", "(U') R' U2 R2 U R  U' R' U R U R2 U' R'", "R U R' U R U2 R'", "(U') R' U2 R U R' U R", "R U R2 U' R2 U' R2 U2 R2 U2 R'", "(U2) R' U' R U' R U R2 U R2 U2 R'", "(U') R U R' U' R' U2 R U R U' R' U R' U R", "(U') R' U' R U R U R' U' R' U R U R U' R'", "R U R' U R U' R' U R' U' R2 U' R' U R' U R", "R U R' U R U R U R U R U' R' U' R2", "(U) R U R' U R' U' R2 U' R' U R' U' R U R' U R", "R U R' U R U' R' U R' U' R' U R U' R' U' R2 U R"],
    "S2": ["F U' R' U R U F' R U R2 U R2 U2 R'", "(U) R' D' R U' R' D R U2 R U R' U2 R U R'", "R' U2 R U R' U' R F U' R' U' R U F'", "R' U R U2 R' U R U2 R D R' U' R D' R'", "L' U2 R U' R' U2 L U R U' R' U R U2 R'", "(U) F R U R' U' R U R2 U' F' U R U R U' R'", "(U2) R U R' F' R U R' U R U2 R' F R U' R'", "(U) R U2 L' R' U2 R U2 R' U2 L U' R U' R'", "(U') R U' R2 U2 D' R U R' U D R2 U R'", "(U) F U R' F R F' R U' R' U R U' R' F'", "R U R' U' L' U R U' L U' L' U R' U' L", "(U2) r' F2 R F' r U' R' U r' F r U2 R U2 R'"],
    "S3": ["R U' L' U R' U' L", "(U) R' U2 R U R' U' R' D' R U2 R' D R2", "(U') R' D U' R' U R U2 D' R2 U R' U' R'", "(U) R' U' R' U R2 D' U2 R U R' U' D R'", "R2 D R' U2 R D' R' U' R' U R U2 R'", "D' R U R' U R U' R' U' D R2 U' R U' R' U R' U R2", "R U R' U R U R' U' R U R D R' U' R D' R' U2 R'", "(U') R' U2 R U R' U' R' D' R U' R' D R U R U' R' U' R", "(U') R' U2 F' R U R' U' R' F R U2 R", "R2 U R U R' U' R' U' R' L' U R' U' L", "(U) R U2 R' U2 R' F R2 U R' U' R U R' U' F'", "R U R' U R U' R' U' R' F R2 U' R' U' R U R' F'"],
    "S4": ["R' D R2 D' R2 U R2 D R2 D' R2 U' R'", "(U') R U R' U R U' R D R' U' R D' R2", "(U2) R U' R' U' R U' R' U2 R U R2 D' R U2 R' D R", "(U) F U R U' R' U R U' l U' R2 D' R U R' x", "(U2) R2 D' R U' R' D R U' R U R' U R", "(U) R U2 R' L' U2 R U R' U2 L R U2 R'", "R' D' R U R' D R2 U' R' U R U R' U' R U2 R' U R U2 R'", "R U' R' U' R U R D R' U2 R D' R2 U R U2 R'", "(U') R' U2 R' D' R U R' D R U' R U R' U R", "(U) R' U' R U' R2 F' R U R U' R' F U2 R", "(U2) R U R' U R' D' R U R' D R U' R U2 R'", "(U2) R U2 R' U' R U R' U' R U R D R' U2 R D' R2"],
    "S5": ["f R' F' R U2 R U2 R' U2 S'", "(U) R' D' R U R' D R2 U R' U2 R U R'", "R' D R' U R D' U R U' R' U' R2 U R U' R'", "(U) R' U2 R U R2 D' R U' R' D R U2 R", "(U2) R2 D' r U2 r' D R2 U R' U R", "R' U2 R U R' U R' D' R U2 R' D R U2 R", "R L' U R' U' L U2 R U2 R'", "(U2) R2 D' R U2 R' D R2 U R' U R", "R2 F R U R U' R' F' R U' R' U R", "(U) R U R' U R' U' R' D' R U R' D R' U2 R'", "(U') R' U' F U' R2 U R2 U F' R U' R U' R'", "(U') R' U' R' D' R U' R' D R' U R2 U R U' R U' R'"],
    "S6": ["(U2) R U R' U' R U R2 D' R U2 R' D R2 U2 R'", "R U R' U R U' R2 F' R U R U' R' F R U' R'", "(U2) R U R' U R2 D r' U2 r D' R2", "R' U R U2 R' U R2 D R' U R D' R'", "(U') R' U' R U R2 U' R' U' R U D' R U R' D R'", "(U2) R U R' U R2 D R' U2 R D' R2", "(U2) R' U2 R U2 L U' R' U L' R", "R U2 R D R' U2 R D' R' U R' U R U2 R'", "R U R2 F' R U2 R U2 R' F R U' R'", "(U) R U R' U' R U R2 D' R U R' D R U R U2 R'", "F' R U R' U R U2 R' F U R U' R' U2 R U' R'", "(U) R' F R U R' U' R' F' D' R U R' D R2"],

    "AS1": ["(U) R U' R2 U' R U' R' U2 R' U2 R' U' R U' R2", "(U) R U2 R2 U' R' U R U' R' U' R2 U R", "R' U' R U' R' U2 R", "(U) R U2 R' U' R U' R'", "R' U' R2 U R2 U R2 U2 R2 U2 R", "(U2) R U R' U R' U' R2 U' R2 U2 R", "(U) R' U' R U R U2 R' U' R' U R U' R U' R'", "(U) R U R' U' R' U' R U R U' R' U' R' U R", "(U) R U R' U R' U' R U R' U' R2 U' R2 U R U' R' U R", "R' U' R U' R' U' R' U' R' U' R' U R U R2", "(U) R U R' U' R U R2 U' R2 U' R' U R U' R' U R' U R", "(U2) R U R' U R' U' R' U R U' R' U' R' U' R' U2 R"],
    "AS2": ["(U') R U2 R2 U' R2 U' R' F U' R' U' R U F'", "(U') R D R' U R D' R' U2 R' U' R U2 R' U' R", "(U') R U2 R' U' R U R' L' U R U' L U2 R'", "R U' R' U2 R U' R' U2 R' D' R U R' D R", "(U') F U' R' U R U F' R' U R U' R' U2 R", "(U) R U R' U L' U2 R U2 R' U2 R L U2 R'", "R U R' F' R U2 R' U' R U' R' F R U' R'", "R U  R' U' R' U' F U R2 U' R' U R U' R' F'", "(U) R' U R2 U2 D R' U' R U' D' R2 U' R", "R' U R U R' U r U' R' U R U r' R' F R F' U R", "z D' R' D R U R' D' R U' R U R' D R U' z'", "R U2 R' U' R U r' F r U2 R' U' r' F2 r"],
    "AS3": ["R' U L U' R U L'", "(U') R U2 R' U' R U R D R' U2 R D' R2", "(U) R D' U R U' R' U2 D R2 U' R U R", "(U') R U R U' R2 D U2 R' U' R U D' R", "R2 D' R U2 R' D R U R U' R' U2 R", "D R' U' R U' R' U R U D' R2 U R' U R U' R U' R2", "R' U' R U' R' U' R U R' U' R' D' R U R' D R U2 R", "(U) R U2 R' U' R U R D  R' U R D' R' U' R' U R U R'", "(U2) F U R U' R' U R U' R2 F' R U2 R U2 R'", "(U2) F R U' R' U R U R2 F' R U R U R' U' R U' R'", "(U2) R' U2 R' F' R U R U' R' F U2 R", "(U2) L' U R U' L R U R U R U' R' U' R2"],
    "AS4": ["R D' R2 D R2 U' R2 D' R2 D R2 U R", "(U) R' U' R U' R' U R' D' R U R' D R2", "l U' R' D R2 U l' U R' U' R U R' U' F'", "(U') R' D' R U2 R' D R2 U' R' U2 R U R' U R U R'", "(U2) R2 D R' U R D' R' U R' U' R U' R'", "(U) R U2 R' L' U2 R U' R' U2 L R U2 R'", "(U') R U R' U' R' U' R U R U' R' U' R2 D' R U' R' D R U2 R", "(U') R U2 R' U' R2 D R' U2 R D' R' U' R' U R U R'", "(U) R U2 R' U R' D' R U' R' D R U' R U' R'", "(U') R2 D R' U2 R D' R' U' R' U R U' R' U  R U2 R'", "(U2) R' U' R U' R D R' U' R D' R' U R' U2 R", "(U2) R' U2 F' R U R' U' R' F R2 U R' U R"],
    "AS5": ["(U') R U2 R2 D' R U2 R' D R2 U' R' U R U' R'", "(U') R D R' U' R D' R2 U' R U2 R' U' R", "R D' R U' R' D U' R' U R U R2 U' R' U R", "R U R' F' R U R' U' R' F R2 U R' U' R U' R'", "(U2) R2 D r' U2 r D' R2 U' R U' R'", "R U2 R' U' R U' R D R' U2 R D' R' U2 R'", "L R' U' R U L' U2 R' U2 R", "(U2) R2 D R' U2 R D' R2 U' R U' R'", "R U R' F' R U2 R' U2 R' F R2 U' R'", "(U') R' U' R U' R U R D R' U' R D' R U2 R", "(U) R U R' U2 R U R' U' F' R U2 R' U' R U' R' F", "R2 D' R U' R' D F R U R U' R' F' R"],
    "AS6": ["(U') R U2 R' U' F' R U R' U' R' F R2 U' R'", "(U') R' U2 R' D' R U R' D R2 U' R' U2 R", "(U2) R' U' R U' R2 D' r U2 r' D R2", "R U' R' U2 R U' R2 D' R U' R' D R", "(U) R U R' U' R2 U R U R' U' D R' U' R D' R", "(U2) R' U' R U' R2 D' R U2 R' D R2", "(U2) R U2 R' U2 L' U R U' R' L", "R' U2 R' D' R U2 R' D R U' R U' R' U2 R", "R' U' R U R' F R U R' U' R' F' R2", "(U) R U2 R D' R U' R' D R U R U' R U' R'", "(U) R U R' U R' F U' R2 U' R2 U F' U R", "(U') R U R' U R' U' R2 U' R D' R U R' D R U R"],

    //"sune cases where you can't just mirror the antisune case in your head (24 algs)": ["F R U R' U' R U R2 U' F' U R U R U' R' ", "F U R' F R F' R U' R' U R U' R' F'", "R' U2 R U R' U' R F U' R' U' R U F'", "L' U2 R U' R' U2 L U R U' R' U R U2 R'", "R U R' F' R U R' U R U2 R' F R U' R'", "R U2 L' R' U2 R U2 R' U2 L U' R U' R'", "R2 U R U R' U' R' U' R' L' U R' U' L", "R' U2 F' R U R' U' R' F R U2 R U", "R U2 R' U2 R' F R2 U R' U' R U R' U' F'", "R U' R' U' R U R D R' U2 R D' R2 U R U2 R' U", "R' U2 R' D' R U R' D R U' R U R' U R", "R' U' R U' R2 F' R U R U' R' F U2 R", "R U2 R' L' U2 R U R' U2 L R U2 R'", "U R U2 R' U' R U R' U' R U R D R' U2 R D' R2", "R' D' R U R' D R2 U' R' U R U R' U' R U2 R' U R U2 R'", "(U') R U2 R2 D' R U2 R' D R2 U' R' U R U' R' ", "R U R' F' R U R' U' R' F R2 U R' U' R U' R'", "R U R' F' R U2 R' U2 R' F R2 U' R'", "(U) R U R' U R' U' R' D R' U' R D' R U2 R", "R2 D' R U' R' D F R U R U' R' F' R ", "R U R' U R U' R2' F' R U R U' R' F R U' R'", "R U R2 F' R U2 R U2 R' F R U' R'", "(U) R U R' U' R U R2 D' R U R' D R U R U2 R'", "(U') R' U2 R' D R' U R D' R U R U' R U' R'", "(U) R' F R U R' U' R' F' D' R U R' D R2"],

}

var ollcp = {
	
	"1":[ "r U R' U R' r2 U' R' U R' r2 U2' r'", "R U2' R2' F R F' U2 R' F R F'", "R U' R2 D' r U' r' D R2 U R'", "F R U R' U' F' r' U r2 U' r2' U' r2 U r'",  ],
	"2":[ "F R U R' U' F' f R U R' U' f'", "R2 F2 r U2 R U' r2 F2 r F R", "r U R' U2 R U2 r2 F2 r F' r' F2 r", "R' F' r' F2 r2 U R' U2 r' F2 R2", "U' R U' R2' D' r U r' D R2 U R'", "r D' R2' U' R U2 R' U R2 D r'",  ],
	"3":[ "U' f R U R' U' f' U' F R U R' U' F'", "U' F' r U R' U r' F2 R U2 R' F R", "f U R U' R' f' F R' F' R U R U' R'", "U R' F2 R2 U2' R' F R U2' R2 F2 R", "U R' D' r U' r' D R U F R' F' R", "U F R U R' U' F' r' U2 R U R' U r",  ],
	"4":[ "U f R U R' U' f' U F R U R' U' F'", "U r U2 r2 F2 r F' R U2 R2 F2 R", "U' R' F' R U2 R' F2 r U' R U' r' F", "U' F R' F' r U' R U2 r' U2 r U' r'", "U' R D r' U r D' R' d' R' F R F", "R' F' U' F U R U' r U2 R' U' R U' r'",  ],
	"5":[ "U' r' U2 R U R' U r", "U' r D' R2 U' R U R' U R2 D r'", "R' F' R U R' U' R' F R F' U F R", "U F U' R2 D R' U R D' R2 U F'", "U2 R U' R' U' F' U R U R' U' R' F R", "r' U2 R U R' U F' U' F U r",  ],
	"6":[ "U r U2 R' U' R U' r'", "U F U' R2 D R' U' R D' R2 U F'", "U F R U' R' U R U2 R' U' F'", "U r' D R2 U R' U' R U' R2 D' r", "R' F R F' U' r' D' r U r' D r", "r U2 R' F R' F' R U' R U' r'",  ],
	"7":[ "r U R' U R U2 r'", "L' U2 L U2 L F' L' F", "F R' F' R U2 R U2 R'", "U2 R' U2 R U R' U R2 U R' U' R' F R F'", "R U' R' U' F' U2' F U2' R U2 R'", "U R' U' F R' F' R U' R U R' U R",  ],
	"8":[ "r' U' R U' R' U2 r", "U F R' F' R U R U' R2 U' R U' R' U2 R", "f' U f R' U2 R' U2 R", "U2 R U2 R' U2 R' F R F'", "U' R U2 R' U2' F' U2' F U R U R'", "R U2 R' F R' F' R U' R U' R'",  ],
	"9":[ "U M R U2 R' U' R U' R' U' M'", "F2 r U r' U2 F R U2 l U' R' U l' ", "U' F R U R' U' R U' R' U R U2 R' U' F'", "U2 R U R' U' R' F R2 U R' U' F'", "U' F' U' F r U' r' U r U r'", "U' R' U' R U' R' U R' F R F' U R",  ],
	"10":[ "U2 M U R' U2 R U R' U R U M'", "L' U' L U L F' L2 U' L U F", "U2 R' U' R U F R U R' U' F' R' U R", "r' U' F2 R U' R' U2 r' F r U' r", "U2 R U R' y R' F R U' R' F' R", "U2 R U R' U R' F R F' R U2 R'",],
	"11":["r' R2 U R' U R U2 R' U M'","U2 r U R' U R2 D R' U2 R D' R' r'","f U R U' R2 F' R U R U' R' S'","U r' U' R U' R' U2 x U R U' L U R'","R2 D r' U' r D' R' U2 R' F' U F","U2 r U R' U R' F R F' R U2 r'",],
	"12":["r R2' U' R U' R' U2 R U' M","U' l U L' U L U2 x U' L' U R' U' L","R2 D' r U r' F r U r' F2 D R2","U F R U' R' F2 u' r U r' D R","R2 D' r U r' D R U2 R y R U' R'","l' U' L U' L F' L' F L' U2 l",],
	"13":["U2 R' U' R U' r U R2 U R2 U2 r'","F U R U2 R' U' R U R' F'","F U R U' R2' F' R U R U' R'","U R' U' R U' R' U R y r U' r' U r U r'","r U' r' U' r U r' F' U F","U2 F U R U' R2 F2 R U2 R U2 R' F",],
	"14":["U2 R U R' U r' U' R2 U' R2' U2' r","U' R U R' U R U' R' y R' F R U' R' F' R","U2 F' U' r' F r2 U r' U' r' F r","U2 F' U' L' U2 L U L' U' L F","r' U r U r' U' r y R U' R'","U' R U2 R' U' R U R2 F R F' R U2 R'",],
	"15":["U' r' U' r R' U' R U r' U r","U2 R' U2 R U R' F U R U' R' F' R","U' L F' L' U' L U F L' U L U2 L'","U' l' U l U l' U' l y' R U R' U' R U' R'","U R U2 R' U' R U R' U' R U R' U2 R' F R F'","U F R U R' U' F' R' U2 R U R' U R",],
	"16":["U r U r' R U R' U' r U' r'","U' r U' r' U' r U r' y' R' U' R U R' U R","U' R' F R U R' U' F' R U' R' U2 R","L U2 L' U' L F' U' L' U L F L'","U F R U R' U' F' U R U' L' U R' U' L","U' F R U R' U' F' R U2 R' U' R U' R'",],
	

}

var COLL = {
	"Sune":["R U R' U R U2' R' ","R U' L' U R' U' L ","U2' R' U' R U' R2' D' R U2 R' D R2 ","U' R U R' U R U' R D R' U' R D' R2' /U2' R2' D' R U' R' D R U' R U R' U R","R2' F R U R U' R' F' R U' R' U R /U2 R2' D' R U2 R' D R2 U R' U R /U R' D' R U R' D R2 U R' U2' R U R'","U2' R U R' F' R U R' U R U2' R' F R U' R' ",],
	"AntiSune":["R' U' R U' R' U2 R ","U2' L' U R U' L U R' ","U2' R' U' R U' R2' D' R U2 R' D R2 ","R U R' F' R U2 R' U' R U' R' F R U' R' ","R U R' F' R U2 R' U2' R' F R2 U' R' /U2 R2 D R' U2' R D' R2' U' R U' R'","U R' U' R U' R' U R' D' R U R' D R2 ",],
	"L":["R U R' U R U' R' U R U' R' U R U2' R' ","U' R U2' R D R' U2 R D' R2' /U2 R' F' R U R' U' R' F R2 U' R' U2 R","U' F R' F' r U R U' r' ","R' U' R U R' F' R U R' U' R' F R2 ","U2 R' U2' R' D' R U2 R' D R2 ","F' r U R' U' r' F R ",],
	"T":["R U2' R' U' R U' R2' U2' R U R' U R ","R' U R U2' L' R' U R U' L /R' U' R' U' R U R' F' R U R' U' R' F R'","U (l' U' L U) (R U' r' F) ","U2 F R U R' U' R U' R' U' R U R' F'","R U R' U' R2 D R' U2 R D' R2' U R U' R'","U' (r U R' U') (r' F R F')",],
	"U":["U2' R U R' U R U2' R2' U' R U' R' U2 R ","U2' R 2 D R' U2 R D' R' U2 R' ","R' F R U' R' U' R U R' F' R U R' U' R' F R F' R /U' r U R' U' r' F R2 U' R' U' R U2 R' U' F'","F R U' R' U R U R' U R U' R' F'/R' U2' R U R' U R' D' R U' R' D R U R","R2' D' R U2 R' D R U2 R ","R2' D' R U R' D R U R U' R' U' R ",],
	"Pi":["R U2' R2' U' R2 U' R2' U2' R ","U' R' U' R U' R' U R U' R' U R' D' R U R' D R2 /R' F2 R U2' R U2' R' F2 U' R U' R'","U' R U R' U F' R U2 R' U2' R' F R /U2' L' U R U' L U' R' U' R U' R'","U R U2 R' U' F' R U2 R' U' R U' R' F R U' R'/r' U' R U' R' U R U' R' U R' F R F' U r/U2 R U2' R' U R' D' R U R' D R2 U' R' U R U' R'","U R U R' U R U' R' U R U' R D R' U' R D' R2'/R U2 R' U' R U R' U2' L' U R U' L R'/U' R U R' U F2 R U2' R' U2' R' F2 R","R' U' F' R U R' U' R' F R2 U2' R' U2 R/U F U R U' R' U R U2' R' U' R U R' F'",],
	"H":["R' U' R U' R' U R U' R' U2 R /R U R' U R U' R' U R U2' R' /U R U2 R' U' R U R' U' R U' R' ","F R U' R' U R U2 R' U' R U R' U' F'","F R U R' U' R U R' U' R U R' U' F'","R' F' R U2 R U2' R' F U' R U' R'/U' l U' R U R' l' U L F' L' U L F L'/R U R' U R U L' U R' U' L",],
}
var test = {
	"test1":["RUR'U'", "U R U2 R' U' F' R U2 R' U' R U' R' F R U' R'/ r' U' R U' R' U R U' R' U R' F R F' U r/ U2 R U2' R' U R' D' R U R' D R2 U' R' U R U' R'","U R U R' U R U' R' U R U' R D R' U' R D' R2'/ R U2 R' U' R U R' U2' L' U R U' L R'/ U' R U R' U F2 R U2' R' U2' R' F2 R"]
}
window.algs = { "ZBLL" :zbll_full, "EG-1": eg_full, "OLLCP": ollcp , "COLL": COLL};
