var zbll_full = {
	"1" :[
		"(U') R U R' U R U2 R' U2 R' U' R U' R' U2 R",
		"R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'",
		"(U2) R' U2 R U R' U R2 U2 R' U' R U' R'",
		"R U2 R' U' R U' R2 U2 R U R' U R",
		"R' U R U2 R' U' R U2 R' U' R U' R' U R",
		"(U2) R U' R' U2 R U R' U2 R U R' U R U' R'",
		"R' U R2 U R' U R' U' R U' R' U' R U R U' R'",
		"(U') R U R' U R U' R' U R' U' R2 U' R2 U2 R",
		"(U2) R' U2 R U R' U R U' R' U' R U' R' U2 R",
		"R U2 R' U' R U' R' U R U R'U R U2 R'",
		"(U') R' U' R2 U R2 U R2 U2 R' U R' U R ",
		"(U') R U R2 U' R2 U' R2 U2 R U' R U' R'",
	],
	"2" :[
		"(U) R U R' U R U R2 D' r U2 r' D R2 U R'",
		"(U) R' U' R U' R' U' R2 D r' U2 r D' R2 U' R",
		"(U2) R U' R2 D' r U2 r' D R2 U R'",
		"R' U R2 D r' U2 r D' R2 U' R",
		"R' U' R U2 R D R' U' R D' R2 U R U' R' U R",
		"(U') R U2 R' U' R U r' F r U2 R' r' F r",
		"R' U' R U R2 D' R U2 R' D R2 U2 R' U2 R",
		"(U) R U R' U' R U R2 D' R U' R' D R U2 R U' R'",
		"(U) R' D' R U' R' D R U' R U' R' U R U' R' U' R U R'",
		"R U' R' U R U R' U' R U R' U R' D' R U R' D R",
		"(U) R U R D R' U R D' R' U L' U R' U' L ",
		"(U2) R2 F R U R' U' R' F' R' U' R2 U2 R U2 R",
	],
	"3" :[
		"R' U R U2 L' R' U R U' L ",
		"R' U2 R U R2 F R U R U' R' F' R",
		"(U2) R' U' R2 U R' F' R U R' U' R' F R2 U' R' U' R' U R",
		"(U2) r U' r U2 R' F R U2 r2 F",
		"(U') R' U' R' D' R U R' D R U2 R U R' U R",
		"R' U' R y R U R' U' R l U' R' U l'",
		"(U) L' U2 R U2 R' U2 L U R U R' U' R U' R'",
		"F U' R' U2 R U F' R' U' R U R' U R",
		"(U2) R' U' R U' R' U R F U' R' U2 R U F'",
		"R U R' U R U' R' U' L' U2 R U2 R' U2 L",
		"R' U2 R U R' U R F U R U2 R' U R U R' F'",
		"r' U' l' U2 R U' R' U2 l R U' R' U2 r",
	],
	"4" :[
		"(U') l' U2 R' D2 R U2 R' D2 R2 x'",
		"R' U2 R U' R' F R U R' U' R' F' R U' R",
		"R' U2 R' D' R U2 R' D R' U R' U R U2 R'",
		"(U2) R U2 R D R' U2 R D' R U' R U' R' U2 R",
		"R' D' R U R' D R U2 R U2 R' U R U R'",
		"(U) R' U' R' D' R U R' D R U' R U' R' U2 R",
		"R' U R2 D R' U R D' R' U R' U' R U' R' U' R ",
		"(U2) R U' R2 D' R U' R' D R U' R U R' U R U R'",
		"(U) R' U' R U' F U' R' U R U F' R' U R",
		"R' D' R U R' D R2 U R' U2 R U' R' U' R U' R'",
		"(U2) F R U R' U' R U' R' U' R U R' F'",
		"(U') R U R' U2 R U' R' U2 R U' R2 F' R U R U' R' F",
	],
	"5" :[
		"R U R D R' U' R D' R2",
		"(U') R U2 R' U2 R' F R U R U' R' F'",
		"(U2) R2 B2 R' U2 R' U2 R B2 R' U R U' R'",
		"(U') R' D' R U R' D R2 U' R' U R U R' U' R U R'",
		"(U') F' U' r' F2 r U' r' F' r F ",
		"(U') R U R' U' R U' R' L U' R U R' L'",
		"(U) R U R' U R U R' U2 L R U' R' U L'",
		"R' U' R U' R2' F' R U R U' R' F U R U' R' U2 R",
		"(U) R' U' R U R' U' R2 D R' U2 R D' R' U R' U R",
		"(U2) R U R D R' U2 R D' R' U' R' U R U' R' U' R U' R'",
		"(U2) F R U R' U' R' F' U2 R U R U' R2 U2 R",
		"(U') R U' R' U' R U R D R' U2 R D' R' U' R'",
	],
	"6" :[
		"x' U' R' D R U R' D' R x",
		"(U) R U R' U' R' F' R U2 R U2 R' F",
		"R2 F2 R U2 R U2 R' F2 R U' R' U R",
		"(U') R D R' U' R D' R2 U R U' R' U' R U R' U' R",
		"(U) F U R U2 R' U R U R' F'",
		"R U R' U' R U' R'  U' F R U R' U' R' F' R",
		"(U) R' U' R U' R' U' R U2 L' R' U R U' L",
		"(U) F R U R' U' R U R' U' F' R U R' U' R' F R F'",
		"(U) R U R' U' R U R2 D' R U2 R' D R U' R U' R'",
		"R' U2 R F U' R' U R U F' R' U R",
		"(U) R' U2 R2 U R' U' R' U2 F' R U2 R U2 R' F",
		"(U') R' U R U R' U' R' D' R U2 R' D R U R",
	],
	"7" :[
		"(U) R U2 R' U' R U' R' U2 R' U2 R U R' U R",
		"R U R' U' R U' R U2 R2 U' R U R' U' R2 U' R2",
		"R' U' R U' R' U2 R2 U R' U R U2 R'",
		"(U2) R U R' U R U2 R2 U' R U' R' U2 R",
		"(U') R U R' U' R U' R' U2 R U' R' U2 R U R'",
		"(U') R' U' R U R' U R U2 R' U R U2 R' U' R",
		"(U) R U2 R2 U' R2 U' R' U R' U' R U R' U R",
		"(U) R' U2 R2 U R2 U R U' R U R' U' R U' R'",
		"(U) R' U2 R U R' U R U R' U' R U' R' U2 R",
		"(U) R U2 R' U' R U' R' U' R U R' U R U2 R'",
		"R' U' R U' R U2 R2 U' R2 U' R2 U R",
		"(U2) R U R' U R' U2 R2 U R2 U R2 U' R'",
	],
	"8" :[
		"R U2 R' U2 R' U' R U R U' R' U2 R' U2 R",
		"R U R' U R U' R' U R U' R' U R U2 R'",
		"(U2) R U2 R' U' R U' R' U2 R U R' U R U2 R'",
		"(U2) R U R' U R U2 R' U2 R U2 R' U' R U' R'",
		"R2 U R' U R' U' R U' R' U' R U R U' R2",
		"(U') R2 U' R U' R U R' U R U R' U' R' U R2",
		"(U) R' U2 R U R' U R U' R U2 R' U' R U' R'",
		"(U2) R U2 R' U' R U' R' U R' U2 R U R' U R",
		"(U) R2 U R' U' R' U R U R' U R U' R U' R2",
		"(U2) R2 U' R U R U' R' U' R U' R' U R' U R2",
		"(U2) R U R' U R U2 R' U R' U' R U' R' U2 R",
		"(U) R' U' R U' R' U2 R U' R U R' U R U2 R'",
	],
	"9" :[
		"R U2 R' U' R U' R' U' R' U' R U' R' U2 R",
		"R' U2 R U R' U R U R U R' U R U2 R'",
		"(U) R' U' R U' R' U R U' R' U2 R",
		"(U') R U R' U R U' R' U R U2 R'",
		"R' U2 R U R' U' R U R' U R",
		"R U2 R' U' R U R' U' R U' R'",
		"(U) R U R' U R U' R' U R U' R' U R' U' R2 U' R' U R' U R",
		"(U) R U R' U R U2 R' U' R' U2 R U R' U R",
	],
	"10" :[
		"R' U' R U R U2 R' U' R U' R2 U2 R",
		"R U R' U' R' U2 R U R' U R2 U2 R'",
		"(U') R' U2 R U R' U R2 U R' U R U2 R'",
		"(U) R U2 R' U' R U' R2 U' R U' R' U2 R",
		"(U') R U2 R' U2 R U' R' U2 R U' R' U2 R U R'",
		"(U) R' U2 R U2 R' U R U2 R' U R U2 R' U' R",
		"(U2) R U' R' U2 R U R' U2 R U R' U2 R U2 R'",
		"(U2) R' U R U2 R' U' R U2 R' U' R U2 R' U2 R",
		"R' U2 R2 U R2 U R2 U2 R'",
		"R U2 R2 U' R2 U' R2 U2 R",
		"R U R' U' R' U' R U R U R' U' R' U R U' R U' R'",
		"R U2 R' U' R U' R' U' R U2 R' U' R U' R'",
	],
	"11" :[
		"(U') R' U R2 U R' U R U2 R U2 R U R' U R2",
		"(U') R' U2 R2 U R  U' R' U R U R2 U' R'",
		"R U R' U R U2 R'",
		"(U') R' U2 R U R' U R",
		"R U R2 U' R2 U' R2 U2 R2 U2 R'",
		"(U2) R' U' R U' R U R2 U R2 U2 R'",
		"(U') R U R' U' R' U2 R U R U' R' U R' U R",
		"(U') R' U' R U R U R' U' R' U R U R U' R'",
		"R U R' U R U' R' U R' U' R2 U' R' U R' U R",
		"R U R' U R U R U R U R U' R' U' R2",
		"(U) R U R' U R' U' R2 U' R' U R' U' R U R' U R",
		"R U R' U R U' R' U R' U' R' U R U' R' U' R2 U R",
	],
	"12" :[
		"(U) R U' R2 U' R U' R' U2 R' U2 R' U' R U' R2",
		"(U) R U2 R2 U' R' U R U' R' U' R2 U R",
		"R' U' R U' R' U2 R",
		"(U) R U2 R' U' R U' R'",
		"R' U' R2 U R2 U R2 U2 R2 U2 R",
		"(U2) R U R' U R' U' R2 U' R2 U2 R",
		"(U) R' U' R U R U2 R' U' R' U R U' R U' R'",
		"(U) R U R' U' R' U' R U R U' R' U' R' U R",
		"(U) R U R' U R' U' R U R' U' R2 U' R2 U R U' R' U R",
		"R' U' R U' R' U' R' U' R' U' R' U R U R2",
		"(U) R U R' U' R U R2 U' R2 U' R' U R U' R' U R' U R",
		"(U2) R U R' U R' U' R' U R U' R' U' R' U' R' U2 R",
	],
	"13" :[
		"(U2) R' U' R U' F U' R' U R U R' U R U' F'",
		"R U R' U L' U R U' M' x' U' R U' R'",
		"(U') R U2 R2 F R F' M' U' R U' R' U M",
		"(U') R' U2 R F U' R' U R U R' U R U' F'",
		"(U2)  R2 D R' U' R D' R' U' R' U R U R'",
		"R2 D' R U R' D R U R U' R' U' R",
		"R U' R' U' R U R D R' U R D' R2",
		"(U2) R' U R U R' U' R' D' R U' R' D R2",
		"M U' M' F R U R' U' F' M U M'",
		"(U') F R U R' U' R U R' U' F' U' R' F' U' F U R",
		"F R U' R' U' R U2 R' U' R U' R' U' R U2 R' U' F'",
		"(U) r' U' R' F R U r F R U' R' F'",
	],
	"14" :[
		"F R U' R' U' R U R D R' U' R D' R' U2 R' U' F'",
		"(U) F R U R' U' R U' R' U2 R U2 R' U' F'",
		"L' U2 R U' R' U2 L R U' R'",
		"R' U' R U R' F' R U R' U' R' F R2",
		"F R U R' U' R' F R2 U' R' U' R U R' F2",
		"R' U' R U R' U' R' F R2 U' R' U' R U R' F' U R",
		"(U) r U2 R r2 F R' F' r2 U2 r'",
		"(U2) r U2 r2 F R F' r2 R' U2 r'",
		"(U2) F R U R' U' F' r U r' U R U' R' r U' r'",
		"(U) r U r' R U R' U' r U' r' F U R U' R' F'",
		"(U) R U2 R' U' L' U2 R U R' L U L' U L",
		"(U) R U R' U' R' U2 R' U D R' U' R U2 D' R",
	],
	"15" :[
		"(U) x' U' R U' R' U R' F2 R U' R U R' U x",
		"F U R U' R' U R U' R' U R U' R' F'",
		"R U R' y' U R' U R U' R2 F R F' R",
		"R' U' R y U' R U' R' U R l U' R' U l'",
		"F R U R' U' R U R' U' F' U R' F' U' F U R",
		"R' U' R U' R' U2 R U R' U' R U R' F' R U R' U' R' F R2",
		"(U) L' U L U' L' U' L U R' U' R U L' U' L U2 R' U' R",
		"(U) R U' R' U R U R' U' L U L' U' R U R' U2 L U L'",
	],
	"16" :[
		"F R2 U' R U' R U' R' U2 R' U R2 F'",
		"(U2) F R2 U' R U2 R U R' U R' U R2 F'",
		"F U R' U' R2 U' R2 U2 R U2 R U R' F'",
		"r' U' R U' R' U R U' R' U R' F R F' U r",
		"(U) R U2 R' U' F' R U2 R' U' R U' R' F R U' R'",
		"(U) R' U' R' D' R U R' D R U2 R' D' R U2 R' D R2",
		"(U') R' U' R U R' U' R2 D R' U R D' R' U R' U2 R",
		"(U) R U R' U' R U R2 D' R U' R' D R U' R U2 R'",
		"(U2) R U2 R' U R' D' R U R' D R2 U' R' U R U' R'",
		"(U2) R' U2 R U' R D R' U' R D' R2 U R U' R' U R",
		"R2 D R' U' R D' R' U' R' U R U' R' U' R U' R'",
		"R2 D' R U R' D R U R U' R' U R U R' U R",
	],
	"17" :[
		"F U' R' U R U F' R U R2 U R2 U2 R'",
		"(U) R' D' R U' R' D R U2 R U R' U2 R U R'",
		"R' U2 R U R' U' R F U' R' U' R U F'",
		"R' U R U2 R' U R U2 R D R' U' R D' R'",
		"L' U2 R U' R' U2 L U R U' R' U R U2 R'",
		"(U) F R U R' U' R U R2 U' F' U R U R U' R'",
		"(U2) R U R' F' R U R' U R U2 R' F R U' R'",
		"(U) R U2 L' R' U2 R U2 R' U2 L U' R U' R'",
		"(U') R U' R2 U2 D' R U R' U D R2 U R'",
		"(U) F U R' F R F' R U' R' U R U' R' F'",
		"R U R' U' L' U R U' L U' L' U R' U' L",
		"(U2) r' F2 R F' r U' R' U r' F r U2 R U2 R'",
	],
	"18" :[
		"(U') R U2 R2 U' R2 U' R' F U' R' U' R U F'",
		"(U') R D R' U R D' R' U2 R' U' R U2 R' U' R",
		"(U') R U2 R' U' R U R' L' U R U' L U2 R'",
		"R U' R' U2 R U' R' U2 R' D' R U R' D R",
		"(U') F U' R' U R U F' R' U R U' R' U2 R",
		"(U) R U R' U L' U2 R U2 R' U2 R L U2 R'",
		"R U R' F' R U2 R' U' R U' R' F R U' R'",
		"R U  R' U' R' U' F U R2 U' R' U R U' R' F'",
		"(U) R' U R2 U2 D R' U' R U' D' R2 U' R",
		"R' U R U R' U r U' R' U R U r' R' F R F' U R",
		"z D' R' D R U R' D' R U' R U R' D R U' z'",
		"R U2 R' U' R U r' F r U2 R' U' r' F2 r",
	],
	"19" :[
		"R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
		"(U') F2 R U' R' U' R U R' F' R U R' U' R' F R F2",
		"R U' R' U R U' L U r' F U2 R U2 R2 x",
		"(U) R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R' U2 R",
		"(U) R U' L U L' U R' U' l U2 R U2 R2 x",
		"(U) R' U L' U' L U' R U l' U2 R' U2 R2 x'",
		"F R U R U2 R' U' R U' R' U2 R' U2 R U' R' U' F'",
		"(U') r U R' U' r' F R2 U' R' U' R U2 R' U' F'",
		"(U) F U R U2 R' U R U R2 F' r U R U' r'",
		"(U') R U2 R' U2 R' F R U R U2 R' U' R U2 R' U' F'",
		"(U') R' U' R F R2 D' R U R' D R2 U' F'",
		"(U') r U R' U' r' F R U R' U' R F' R' U R",
	],
	"20" :[
		"(U') F' r U R' U' r' F R",
		"R' U' R U R' F2 R U2 R' U2 R' F2 R2",
		"(U') F' R U2 R' U2 R' F R U R U' R'",
		"(U) R' U R U' R' U R U R' U' R2 D R' U R D' R'",
		"F R U' R' U' R U2 R' U' F'",
		"(U2) R' U' R U2 R' F' R U R' U' R' F R2 U R' U2 R",
		"R' F R U R U' R' F' U R U R' U R U' R'",
		"R' U R U2 R' L' U R U L U r' F r",
		"(U) F R' F' R U R U' R' F U R U' R' U R U' R' F'",
		"(U') F' R U2 R' U2 R' F U2 R U R U' R2 U2 R",
		"(U2) R U R' U R' D' R U2 R' D R2 U' R' U R U' R'",
		"(U) R' U' R' D' R U2 R' D R U R U' R' U' R",
	],
	"21" :[
		"(U2) R U R' U R U2 R' F R U' R' U' R U2 R' U' F'",
		"l U' R U R' l' U r U' r' U r U r'",
		"(U2) R' F R' F' R2 U' r' U r U' r' U' r",
		"(U) R' U' R U' R' U' L U' R U L'",
		"(U) R U R' U R U L' U R' U' L",
		"(U') R' U' R U' R U R2 U R2 U L' U R' U' L",
		"(U') R U R' U R' U' R2 U' R2 U' L U' R U L'",
		"R U2 R2 U' R' D R' U' R D' R U2 R",
		"R U2 R' U' R2 D R' U R D' R2' U' R U' R'",
		"(U2) R U R' U' L' U2 R U2 R' U L U' r' F2 r",
		"(U') R2 D' R U' R' D R2 U' R2 D' R U2 R' D R2",
		"(U') R2 D R' U R D' R2' U R2 D R' U2 R D' R2'",
	],
	"22" :[
		"(U') F U R U2 R' U R U R' F' R U2 R' U' R U' R'",
		"r U' r' U' r U r' U' l R U' R' U l'",
		"r' U r U r' U' r U R2 F R F' R",
		"r' U' R U' R' U2 r U' R U2 R' U2 R' F R F'",
		"R' U' R U R2 F' R U R U' R' F U' R U R' U R.",
		"R U2 R D' R U' R' D R' U' R2 U2 R",
		"R' U' R U' R2 D' R U R' D R2 U' R' U2 R",
		"(U2) L' U R U' L U' R' U' R U' R'",
		"R U' L' U R' U L U L' U L",
		"(U) R2 D' R U2 R' D R2 U R2 D' R U R' D R2",
		"(U') R2 D R' U2 R D' R2 U' R2 D R' U' R D' R2",
		"(U2) R U2 R' U' R U r' F2 r U2 R' U' r' F r",
	],
	"23" :[
		"R U' L' U R' U' L",
		"(U) R' U2 R U R' U' R' D' R U2 R' D R2",
		"(U') R' D U' R' U R U2 D' R2 U R' U' R'",
		"(U) R' U' R' U R2 D' U2 R U R' U' D R'",
		"R2 D R' U2 R D' R' U' R' U R U2 R'",
		"D' R U R' U R U' R' U' D R2 U' R U' R' U R' U R2",
		"R U R' U R U R' U' R U R D R' U' R D' R' U2 R'",
		"(U') R' U2 R U R' U' R' D' R U' R' D R U R U' R' U' R",
		"(U') R' U2 F' R U R' U' R' F R U2 R",
		"R2 U R U R' U' R' U' R' L' U R' U' L",
		"(U) R U2 R' U2 R' F R2 U R' U' R U R' U' F'",
		"R U R' U R U' R' U' R' F R2 U' R' U' R U R' F'",
	],
	"24" :[
		"R' U L U' R U L'",
		"(U') R U2 R' U' R U R D R' U2 R D' R2",
		"(U) R D' U R U' R' U2 D R2 U' R U R",
		"(U') R U R U' R2 D U2 R' U' R U D' R",
		"R2 D' R U2 R' D R U R U' R' U2 R",
		"D R' U' R U' R' U R U D' R2 U R' U R U' R U' R2",
		"R' U' R U' R' U' R U R' U' R' D' R U R' D R U2 R",
		"(U) R U2 R' U' R U R D  R' U R D' R' U' R' U R U R'",
		"(U2) F U R U' R' U R U' R2 F' R U2 R U2 R'",
		"(U2) F R U' R' U R U R2 F' R U R U R' U' R U' R'",
		"(U2) R' U2 R' F' R U R U' R' F U2 R",
		"(U2) L' U R U' L R U R U R U' R' U' R2",
	],
	"25" :[
		"x R2 U2 R' D2 R U2 R' D2 R' x'",
		"(U2) x R2 D2 R U2 R' D2 R U2 l",
		"R U R' U R U' R' U2 R' D' R U2 R' D R2 U' R'",
		"(U') R' U2 R U R' U R' D R' U2 R D' R' U2 R'",
		"(U') R U' R' U' R U' R' U R' D' R U R' D R2 U R'",
		"(U') R' U R U R' U R U' R D R' U' R D' R2 U' R",
		"R' U2 R U R' U R' D' R U' R' D R U R",
		"R U' R' U' R U2 R' U2 R' D' R U' R' D R",
		"R' U' R U2 R' F' R U R' U' R' F R2 U2 R' U R",
		"(U2) R U R' U R U R' U2 R U' R2 D' R U' R' D R",
		"F R U' R' U R U R' U R U' R' F'",
		"(U) F' R U R' U' R' F R2 U R' U2 R U R' U2 R U' R'",
	],
	"26" :[
		"(U2) F R' F' r U R U' r'",
		"(U') R U R' U' R B2 R' U2 R U2 R B2 R2",
		"(U2) F R U R' U' R' F' R U2 R U2 R'",
		"(U2) R U' R' U R U' R' U' R U R2 D' R U' R' D R",
		"(U) F' r' F r U r' F2 r U F",
		"(U) R U R' U R U R' U' R U R D R' U2 R D' R' U' R'",
		"(U) L R U' R' U R L' U R' U R U' R'",
		"(U) L U' R U R' L' U2 R U' R' U' R U' R'",
		"(U) R' U2 R U R' U' F' R U R' U' R' F R2 U R' U R",
		"(U) R' U2 R2 U R' U' R' U2 F R U R U' R' F'",
		"(U) R U R' U R U' R' U' L' U R U' M' x'",
		"(U2) R U R D R' U2 R D' R' U' R' U R U R'",
	],
	"27" :[
		"(U2) F R' F' r U R U' r2 F2 r U r' F r",
		"(U) R U R' U' R' F R U R U' R' F' R U R' U R U2 R'",
		"R' U2 R U' L U2 R' U2 R U2 L' R' U R",
		"R U2 R' U L' U2 R U2 R' U2 L R U' R'",
		"(U') F U' R U2 R' U2 R U' R' U' R U R' U F'",
		"(U') R' F R U R' U' F' R U' R' U R' F R F' U R",
		"(U') R U2 R' U' R U' R D' R U' R' D R U R",
		"R U2 R2 F U' R2 U' R2 U F' U R",
		"(U2) R' U2 R U2' R2 F' R U R U' R' F U R",
		"(U') F B' R2 B R2 U' R2 U' R2 U R2 F'",
		"(U2) F R U R' U' R' F' U2 R U R' U R2 U2 R'",
		"(U) F R U' R' U R U2 R' U' R U R' U' F'",
	],
	"28" :[
		"(U) R U2 R2 U' R U' R' U2 F R U R U' R' F'",
		"(U') R U R' U R U2 R2 F' r U R U' r' F",
		"(U') r' F' r U' r' F2 r2 U R' U' r' F R F'",
		"F R U R' U' R' F' R U2 R' U' R2 U' R2 U2 R",
		"(U) R' U' R L U2 R' U2 R U2 L' U R' U2 R",
		"(U') F U' R U' R' U R U R' U2 R U2 R' U F' U",
		"(U) R2 D' R U' R' D R U R' D' R U R' D R U R U' R' U' R",
		"R' U' F' R U R' U' R' F R2 U2' R' U2 R",
		"(U') R U R' U R U' R' U' R' F' R U2 R U2' R' F",
		"(U2) R' U' R' D' R U R' D R' U R' U R U2 R'",
		"(U2) R U R D R' U' R D' R U' R U' R' U2 R",
		"(U) F U R U' R' U R U2 R' U' R U R' F'",
	],
	"29" :[
		"R' D R2 D' R2 U R2 D R2 D' R2 U' R'",
		"(U') R U R' U R U' R D R' U' R D' R2",
		"(U2) R U' R' U' R U' R' U2 R U R2 D' R U2 R' D R",
		"(U) F U R U' R' U R U' l U' R2 D' R U R'",
		"(U2) R2 D' R U' R' D R U' R U R' U R",
		"(U) R U2 R' L' U2 R U R' U2 L R U2 R'",
		"R' D' R U R' D R2 U' R' U R U R' U' R U2 R' U R U2 R'",
		"R U' R' U' R U R D R' U2 R D' R2 U R U2 R'",
		"(U') R' U2 R' D' R U R' D R U' R U R' U R",
		"(U) R' U' R U' R2 F' R U R U' R' F U2 R",
		"(U2) R U R' U R' D' R U R' D R U' R U2 R'",
		"(U2) R U2 R' U' R U R' U' R U R D R' U2 R D' R2",
	],
	"30" :[
		"R D' R2 D R2 U' R2 D' R2 D R2 U R",
		"(U) R' U' R U' R' U R' D' R U R' D R2",
		"l U' R' D R2 U l' U R' U' R U R' U' F'",
		"(U') R' D' R U2 R' D R2 U' R' U2 R U R' U R U R'",
		"(U2) R2 D R' U R D' R' U R' U' R U' R'",
		"(U) R U2 R' L' U2 R U' R' U2 L R U2 R'",
		"(U') R U R' U' R' U' R U R U' R' U' R2 D' R U' R' D R U2 R",
		"(U') R U2 R' U' R2 D R' U2 R D' R' U' R' U R U R'",
		"(U) R U2 R' U R' D' R U' R' D R U' R U' R'",
		"(U') R2 D R' U2 R D' R' U' R' U R U' R' U  R U2 R'",
		"(U2) R' U' R U' R D R' U' R D' R' U R' U2 R",
		"(U2) R' U2 F' R U R' U' R' F R2 U R' U R",
	],
	"31" :[
		"R2 D' r U2 r' D R U2 R",
		"R2 D' R U2 R' D R U2 R",
		"R U' R' D R' U' R D' R2 U R' U' R' U2 R'",
		"(U2) R U R' U R U2 R2 U z U R' D R U' z'",
		"(U) R2 D' R U' R' D R2 U' R' U2 R",
		"(U') R' U R U R' U2 R U2 y R U' R' U2 R U' R'",
		"(U') R2 D R' U R D' R2 U' R U' R' U2 R U' R' U2 R U R'",
		"(U) R U L' U R' U' L U' R U R' U R U' R'",
		"(U') R' U2 R2 D R' U2 R D' R2 U R U2 R' U2 R",
		"(U') R U R' U2 F2 R U2 R' U2 R' F2 R2 U R'",
		"(U') R' U2 R' D' R U2 R' D R U2 R U R' U R",
		"(U') R' U R U' R' U' R U2 R D R' U' R D' R2 U' R",
	],
	"32" :[
		"(U) R' U2 R' D' R U2 R' D R2",
		"(U) R' U2 R' D' r U2 r' D R2",
		"(U2) R D R' U2 R D' R' U' R' U2 R U' R' U' R",
		"(U2) R U2 R U R U' R2 D R' U R D' R U R'",
		"(U) R U R' U2 R U R' U2 y' R' U2 R U' R' U' R",
		"R' U2 R U R2 D' R U R' D R2",
		"(U) R U R' U' R U' R' U L' U R U' L U' R'",
		"(U) R U' R' U2 R U R' U2 R U R' U R2 D R' U' R D' R2",
		"(U) R' U2 R U2 R' U' R2 D R' U2 R D' R2 U2 R",
		"(U2) F' R U R' U' R' F R2 U' R' U' R U' R' U R U R'",
		"R U' R2 F2 R U2 R U2 R' F2 U2 R U' R'",
		"(U) R' U R2 D R' U R D' R' U2 R' U R U R' U' R",
	],
	"33" :[
		"r' F' r U r U2 r' F2 U' R U R' U' R U' R'",
		"(U2) R U2 R' U2 R' F R2 U' R' U2 R U2 R' U' F'",
		"R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R",
		"R' L U2 R2 U R2 U R U L' U' R U2 R'",
		"l U2 l' U2 R' U2 R B2 U R' U R",
		"(U') R U R' U F2 R U2 R' U2 R' F2 R",
		"(U') R' U2 R U R' U R2 U' L' U R' U' L",
		"(U) R U R' U R U' R' U R U' R D R' U' R D' R2",
		"R U R' U' R' F R2 U R' U' R U R' U' F'",
		"(U2) R' U' R U' R' U' R U' x' U L' U L U2 R U' R' U x",
		"R U2 R' U' R U R' U2 L' U R U' M' x'",
		"(U') L R' U' R U L' U2 R' U R U' R' U2 R",
	],
	"34" :[
		"f R' F' R U2 R U2 R' U2 S'",
		"(U) R' D' R U R' D R2 U R' U2 R U R'",
		"R' D R' U R D' U R U' R' U' R2 U R U' R'",
		"(U) R' U2 R U R2 D' R U' R' D R U2 R",
		"(U2) R2 D' r U2 r' D R2 U R' U R",
		"R' U2 R U R' U R' D' R U2 R' D R U2 R",
		"R L' U R' U' L U2 R U2 R'",
		"(U2) R2 D' R U2 R' D R2 U R' U R",
		"R2 F R U R U' R' F' R U' R' U R",
		"(U) R U R' U R' U' R' D' R U R' D R' U2 R'",
		"(U') R' U' F U' R2 U R2 U F' R U' R U' R'",
		"(U') R' U' R' D' R U' R' D R' U R2 U R U' R U' R'",
	],
	"35" :[
		"(U') R U2 R2 D' R U2 R' D R2 U' R' U R U' R'",
		"(U') R D R' U' R D' R2 U' R U2 R' U' R",
		"R D' R U' R' D U' R' U R U R2 U' R' U R",
		"R U R' F' R U R' U' R' F R2 U R' U' R U' R'",
		"(U2) R2 D r' U2 r D' R2 U' R U' R'",
		"R U2 R' U' R U' R D R' U2 R D' R' U2 R'",
		"L R' U' R U L' U2 R' U2 R",
		"(U2) R2 D R' U2 R D' R2 U' R U' R'",
		"R U R' F' R U2 R' U2 R' F R2 U' R'",
		"(U') R' U' R U' R U R D R' U' R D' R U2 R",
		"(U) R U R' U2 R U R' U' F' R U2 R' U' R U' R' F",
		"R2 D' R U' R' D F R U R U' R' F' R",
	],
	"36" :[
		"R' U2 R U R2 F' R U R U' R' F R",
		"(U2) R2 D R' U2 R D' R' U2 R'",
		"R' U' R U R U R' U' R' U F R U R U' R' F'",
		"R U' R' U' R U2 R' U' R' D' R U2 R' D R",
		"(U) R U R2 D' R U R' D R2 U2 R'",
		"(U') R U' R' U' R U2 R' U2 y' R' U R U2 R' U R",
		"(U) R' U R' U' D' R U' R' U2 R U' R' D R U' R",
		"(U) R' U' L U' R U L' U R' U' R U' R' U R",
		"(U') R' U' R U R' U R U2 F R' U R U' F' R' U2 R",
		"(U) R U R' U R U' R' U R U' R' U' L' U R U' R' L",
		"(U') R U2 R D R' U2 R D' R' U2 R' U' R U' R'",
		"(U') R U' R' U R U R' U2 R' D' R U R' D R2 U R'",
	],
	"37" :[
		"(U2) R U2 R D R' U2 R D' R2",
		"(U) R' F' R U R' U' R' F R2 U' R' U2 R",
		"(U') L' U R U' L U R2 U2 R U R' U R",
		"(U') F R U R' U' R' F' U' R U R U' R' U' R' U R",
		"(U2) R' U' R U2 R' U' R y U2 R U2 R' U R U R'",
		"(U') R U2 R' U' R2 D R' U' R D' R2",
		"(U2) R' U' R U R' U R U' L U' R' U L' U R",
		"(U2) R' U R' D' R U R' U2 R U R' D U R U' R",
		"(U2) R U2 R' U2 R U R2 D' R U2 R' D R2 U2 R'",
		"(U') R U R' U R U2 R D R' U2 R D' R' U2 R'",
		"(U') R' U R2 B2 R' U2 R' U2 R B2 U2 R' U R",
		"(U2) R U' R2 D' R U' R' D R U2 R U' R' U' R U R'",
	],
	"38" :[
		"(U') R U R' U R U' R' U F2 r U2 r' U' r' F r",
		"(U) F U R U2 R' U2 R U R2 F' R U2 R U2 R'",
		"R U' R' U' R U' R' U R U R' U R' F' R U R U' R' F",
		"R L' U2 R2 U' R2 U' R' U' L U R' U2 R",
		"R' F2 R U2 R U2 R' F2 U' R U' R'",
		"(U) R' U' R U' B2 R' U2 R U2 l U2 l'",
		"(U) R U2 R' U' R U' R2 U L U' R U L'",
		"(U') R' U' R U' R' U R U' R' U R' D' R U R' D R2",
		"(U) F U R U' R' U R U' R2 F' R U R U' R'",
		"R U R' U R U2 R' U' R L' U R' U' L U2 R U2 R'",
		"R' U2 R U R' U' R U2 L U' R' U R L'",
		"(U) R L' U R' U' L U2 R U' R' U R U2 R'",
	],
	"39" :[
		"(U2) R U R' U' R U R2 D' R U2 R' D R2 U2 R'",
		"R U R' U R U' R2 F' R U R U' R' F R U' R'",
		"(U2) R U R' U R2 D r' U2 r D' R2",
		"R' U R U2 R' U R2 D R' U R D' R'",
		"(U') R' U' R U R2 U' R' U' R U D' R U R' D R'",
		"(U2) R U R' U R2 D R' U2 R D' R2",
		"(U2) R' U2 R U2 L U' R' U L' R",
		"R U2 R D R' U2 R D' R' U R' U R U2 R'",
		"R U R2 F' R U2 R U2 R' F R U' R'",
		"(U) R U R' U' R U R2 D' R U R' D R U R U2 R'",
		"F' R U R' U R U2 R' F U R U' R' U2 R U' R'",
		"(U) R' F R U R' U' R' F' D' R U R' D R2",
	],
	"40" :[
		"(U') R U2 R' U' F' R U R' U' R' F R2 U' R'",
		"(U') R' U2 R' D' R U R' D R2 U' R' U2 R",
		"(U2) R' U' R U' R2 D' r U2 r' D R2",
		"R U' R' U2 R U' R2 D' R U' R' D R",
		"(U) R U R' U' R2 U R U R' U' D R' U' R D' R",
		"(U2) R' U' R U' R2 D' R U2 R' D R2",
		"(U2) R U2 R' U2 L' U R U' R' L",
		"R' U2 R' D' R U2 R' D R U' R U' R' U2 R",
		"R' U' R U R' F R U R' U' R' F' R2",
		"(U) R U2 R D' R U' R' D R U R U' R U' R'",
		"(U) R U R' U R' F U' R2 U' R2 U F' U R",
		"(U') R U R' U R' U' R2 U' R D' R U R' D R U R",
	]
};

function getZBLL(){
	
	return zbll_full;
	
}
